// Guide cross-reference checker. Plain Node, no browser — same class of tool
// as validate.mjs, and it exists for the same reason: docs/GUIDE.md was
// generated by reading src/data/ once, and nothing stops the two drifting
// apart the next time a room, item or charm is added, renamed or removed.
//
// Two directions, both load-bearing:
//   1. GUIDE -> DATA: every room reference (`mapId/roomKey`), item id and
//      charm id the guide names in backticks must exist in the live registry
//      installData() actually builds. A typo'd or stale reference fails here.
//   2. DATA -> GUIDE: every heartPiece placement found by scanning
//      src/data/*.js must be mentioned in the guide's heart-piece list, by
//      its room reference. A heart piece the guide forgot fails here.
//
// Usage: node tools/check-guide.mjs

import { readFileSync, readdirSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { installData } from '../src/data/index.js';
import { MAPS } from '../src/world/maps.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const GUIDE_PATH = join(ROOT, 'docs', 'GUIDE.md');

installData();

let pass = 0;
const failures = [];
function check(name, cond, detail) {
  if (cond) { pass++; console.log('  ok   ' + name); }
  else { failures.push(name + (detail ? ' — ' + detail : '')); console.log('  FAIL ' + name + (detail ? ' — ' + detail : '')); }
}

const guide = readFileSync(GUIDE_PATH, 'utf8');

// ---------------------------------------------------------------------------
// Known-identifier registries, read straight out of the engine's own data.
// ---------------------------------------------------------------------------

// Item ids: the top-level keys of ITEMS in src/game/items.js. Read by regex
// against the source rather than imported, because items.js pulls in DOM-ish
// engine modules (game.js et al.) that are not meant to boot outside a page —
// the same reasoning validate.mjs uses for not importing game/*.js directly.
const itemsSrc = readFileSync(join(ROOT, 'src', 'game', 'items.js'), 'utf8');
const itemsBlockMatch = itemsSrc.match(/export const ITEMS = \{([\s\S]*)\n\};/);
if (!itemsBlockMatch) { console.error('could not find ITEMS block in src/game/items.js'); process.exit(2); }
const ITEM_IDS = new Set(
  [...itemsBlockMatch[1].matchAll(/^\s*([a-zA-Z][a-zA-Z0-9]*):\s*\{/gm)].map(m => m[1])
);

// Charm ids: the top-level keys of CHARMS in src/game/scrimshaw.js.
const scrimSrc = readFileSync(join(ROOT, 'src', 'game', 'scrimshaw.js'), 'utf8');
const charmsBlockMatch = scrimSrc.match(/export const CHARMS = \{([\s\S]*?)\n\};/);
if (!charmsBlockMatch) { console.error('could not find CHARMS block in src/game/scrimshaw.js'); process.exit(2); }
const CHARM_IDS = new Set(
  [...charmsBlockMatch[1].matchAll(/^\s*([a-zA-Z][a-zA-Z0-9]*):\s*\{/gm)].map(m => m[1])
);

// Enemy and boss ids: every defineEnemy('id', ...) / defineBoss('id', ...)
// call across src/data/enemies.js and src/data/bosses.js.
function idsFromCalls(file, fn) {
  const src = readFileSync(join(ROOT, 'src', 'data', file), 'utf8');
  return [...src.matchAll(new RegExp(fn + "\\('([a-zA-Z][a-zA-Z0-9]*)'", 'g'))].map(m => m[1]);
}
const ENEMY_IDS = new Set(idsFromCalls('enemies.js', 'defineEnemy'));
const BOSS_IDS = new Set([...idsFromCalls('bosses.js', 'defineBoss')]);

// Map (dungeon/overworld/cave/interior) ids: whatever installData() actually
// registered.
const MAP_IDS = new Set(MAPS.keys());

// Pickup 'kind' values and other short vocabulary the guide is allowed to
// backtick that are not themselves item/charm/enemy/boss/map ids.
const OTHER_KNOWN = new Set([
  'heartPiece', 'heartContainer', 'blank', 'dungeonMap', 'rupee20', 'rupee',
  'fairy', 'key', 'bossKey', 'chartstone', 'bottle', 'coin',
]);

// Dialogue and cutscene ids: the keys of DIALOGUE and CUTSCENES in
// src/data/story.js. The guide's trading-sequence and item-source writeups
// name these directly (e.g. `makuMaster`, `tradeKettle`) as evidence for
// what is and isn't wired up, so they are legitimate backticked references,
// not typos to flag.
const storySrc = readFileSync(join(ROOT, 'src', 'data', 'story.js'), 'utf8');
const STORY_IDS = new Set(
  [...storySrc.matchAll(/^\s*([a-zA-Z][a-zA-Z0-9]*):\s*(?:'|"|\[|`)/gm)].map(m => m[1])
);

// Removed/historical/engine vocabulary the guide legitimately quotes in
// prose while explaining what changed or how something is implemented —
// mostly in the Disagreements section, which by design discusses ids that
// do NOT exist in the live registries any more. Verified by hand against
// docs/GAME-PLAN.md, docs/ITEMS.md and the relevant src/ files at the time
// this guide was written; check-guide.mjs cannot verify a NEGATIVE claim
// (that an id does NOT exist), only that a POSITIVE reference resolves.
const REMOVED_OR_ENGINE_VOCAB = new Set([
  // Old GAME-PLAN.md items/gates this build does not implement (Disagreements).
  'feather', 'bracelet', 'flippers', 'boomerang', 'hookshot', 'magnet',
  'shovel', 'slingshot', 'ringbox', 'abyssPlug', 'saltVane', 'cliffCracked',
  // Keyboard/input names (Part 1 controls).
  'Enter', 'Shift', 'Tab',
  // Engine API and room-script vocabulary named in prose to point at where a
  // behaviour lives (push-block puzzles, the dead makuOpenedKeep flag, the
  // buried/dredge search, defineBoss/isBoss for the miniboss note).
  'buried', 'hold', 'push', 'giver', 'isBoss', 'defineBoss', 'openCharmCases',
  'intro', 'makuOpenedKeep',
]);

const ALL_KNOWN_IDS = new Set([
  ...ITEM_IDS, ...CHARM_IDS, ...ENEMY_IDS, ...BOSS_IDS, ...MAP_IDS, ...OTHER_KNOWN,
  ...STORY_IDS, ...REMOVED_OR_ENGINE_VOCAB,
]);

console.log(`  registries: ${ITEM_IDS.size} items, ${CHARM_IDS.size} charms, ${ENEMY_IDS.size} enemies, ${BOSS_IDS.size} bosses, ${MAP_IDS.size} maps`);

// ---------------------------------------------------------------------------
// Direction 1: every backticked token the guide names must resolve.
// ---------------------------------------------------------------------------

// Room references look like `mapId/floor,x,y` — e.g. `d1/0,3,2` or
// `overworld/0,8,8` or `cave3/0,0,0`.
const ROOM_REF_RE = /`([a-zA-Z][a-zA-Z0-9]*)\/(-?\d+),(-?\d+),(-?\d+)`/g;
const roomRefs = [...guide.matchAll(ROOM_REF_RE)];
console.log(`  guide names ${roomRefs.length} room references`);

const badRooms = [];
for (const m of roomRefs) {
  const [, mapId, f, x, y] = m;
  const map = MAPS.get(mapId);
  if (!map) { badRooms.push(`${mapId}/${f},${x},${y} (no such map '${mapId}')`); continue; }
  // Resolve through occupancy the same way world/maps.js#getRoom does: a
  // multi-screen room's covered cells have no roomDef of their own.
  const key = `${f},${x},${y}`;
  let resolved = !!map.roomDefs[key];
  if (!resolved) {
    for (const [defKey, def] of Object.entries(map.roomDefs)) {
      const [df, dx, dy] = defKey.split(',').map(Number);
      if (df !== Number(f)) continue;
      const [sw, sh] = def.size || [1, 1];
      if (Number(x) >= dx && Number(x) < dx + sw && Number(y) >= dy && Number(y) < dy + sh) { resolved = true; break; }
    }
  }
  if (!resolved) badRooms.push(`${mapId}/${f},${x},${y} (no room at that cell)`);
}
check('every room reference in the guide resolves to a real room', badRooms.length === 0,
  badRooms.slice(0, 20).join('; '));

// Bare identifier tokens: single backticked words with no slash, no space,
// starting with a letter. Skip common markdown/code noise by requiring at
// least one lowercase letter (so `A`, `B`, `L`, `HIGH` — buttons and legend
// letters — are not flagged) and by ignoring the tide-level words and a
// handful of engine constants the guide's prose legitimately quotes.
const BARE_RE = /`([a-zA-Z][a-zA-Z0-9]*)`/g;
const PROSE_ALLOW = new Set([
  'LOW', 'MID', 'HIGH', 'noTide', 'tideForce', 'F', 'SOLID', 'PIT', 'VOID',
  'canPlant', 'canOccupy', 'tryPush', 'dragBack',
]);
const bareTokens = new Set();
for (const m of guide.matchAll(BARE_RE)) {
  const t = m[1];
  if (!/[a-z]/.test(t)) continue; // ALLCAPS button/legend names
  if (PROSE_ALLOW.has(t)) continue;
  bareTokens.add(t);
}
const unknownIds = [...bareTokens].filter(t => !ALL_KNOWN_IDS.has(t)).sort();
check('every backticked item/charm/enemy/boss/map id in the guide is real',
  unknownIds.length === 0, unknownIds.join(', '));

// ---------------------------------------------------------------------------
// Direction 2: every heartPiece placement in src/data/ is mentioned by the
// guide's heart-piece list, keyed by room reference.
// ---------------------------------------------------------------------------

function findHeartPieces() {
  const found = [];
  for (const [mapId, map] of MAPS) {
    for (const [key, def] of Object.entries(map.roomDefs)) {
      // Entity tuples are ['kind', x, y, opts] — the options object carrying
      // `kind: 'heartPiece'` sits at index 3, not 2 (that's y).
      const scan = (list) => {
        for (const e of list || []) {
          if (Array.isArray(e) && e.length >= 4 && e[3] && e[3].kind === 'heartPiece') {
            found.push(`${mapId}/${key}`);
          }
        }
      };
      scan(def.entities);
      for (const b of def.buried || []) {
        if (b[2] === 'heartPiece') found.push(`${mapId}/${key}`);
      }
      // Puzzle-reward spawns (e.g. d3 Reed Cell: clear the room, a heart
      // piece rises) sit inside `puzzle.reward.spawn`, not `entities`.
      if (def.puzzle && def.puzzle.reward && Array.isArray(def.puzzle.reward.spawn)) {
        for (const e of def.puzzle.reward.spawn) {
          if (Array.isArray(e) && e.length >= 4 && e[3] && e[3].kind === 'heartPiece') {
            found.push(`${mapId}/${key}`);
          }
        }
      }
    }
  }
  return found;
}

const dataHeartPieces = findHeartPieces();
console.log(`  src/data/ holds ${dataHeartPieces.length} heartPiece placements`);

const guideHeartRoomRefs = new Set(roomRefs.map(m => `${m[1]}/${m[2]},${m[3]},${m[4]}`));
const missingFromGuide = dataHeartPieces.filter(ref => !guideHeartRoomRefs.has(ref));
check('every heartPiece in src/data/ is referenced in the guide',
  missingFromGuide.length === 0, missingFromGuide.join(', '));

// The guide should also claim the right total, in its own "Heart Piece N"
// numbering, so a future edit that silently drops one from the list (while
// still mentioning its room elsewhere) is still caught.
// A number may legitimately appear more than once — Part 2's dungeon writeups
// cross-reference a heart piece inline ("Heart Piece 11 (see Part 3)") in
// addition to Part 3's own numbered entry for it — so this checks the SET of
// numbers used is exactly {1..N} with no gap, not that each appears once.
const heartHeadings = [...guide.matchAll(/\*\*Heart Piece (\d+)\*\*/g)].map(m => Number(m[1]));
const headingSet = new Set(heartHeadings);
const expectedCount = dataHeartPieces.length;
const expectedSet = new Set(Array.from({ length: expectedCount }, (_, i) => i + 1));
const missingNums = [...expectedSet].filter(n => !headingSet.has(n));
const extraNums = [...headingSet].filter(n => !expectedSet.has(n));
check(`the guide numbers heart pieces 1..${expectedCount} with no gaps`,
  missingNums.length === 0 && extraNums.length === 0,
  `missing: ${missingNums.join(',')}; unexpected: ${extraNums.join(',')}`);

// ---------------------------------------------------------------------------
console.log(`\n=== ${pass} passed, ${failures.length} failed ===`);
if (failures.length) process.exit(1);
