#!/usr/bin/env python3
"""Extract NPC sprites from the Oracle of Seasons NPC sheet.

Sprites ripped by Trailsdegamer / edited by unknown, via spriters-resource.com;
the original artwork is Nintendo's. Fan-work use only.

Regenerate with:  python3 tools/rip-npcs.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from ripkit import load, background, find_cells, quantise, emit_module

SHEET = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    'assets', 'sheets', 'oracle-seasons-npcs.png')

# Cell index on the detected grid -> engine sprite name.
# Indices come from the contact sheet written by tools/ripkit.contact_sheet.
FRAMES = {
    'npc_villager': 0,
    'npc_villager2': 6,
    'npc_fisher': 22,
    'npc_child': 70,
    'npc_elder': 66,
    'npc_shopkeeper': 32,
    # The sheet has no oracle, so Farore borrows a townswoman and is recoloured
    # green below — the Oracle series' own palette-swap trick.
    'npc_farore_0': 54,
    'npc_farore_1': 55,
    'npc_zelda': 25,
}

# Palette overrides, applied after quantisation.
PAL_OVERRIDE = {
    'npc_farore_0': ['#e8f8d8', '#78d888', '#2c8058', '#000000'],
    'npc_farore_1': ['#e8f8d8', '#78d888', '#2c8058', '#000000'],
}


def main():
    im, px, W, H = load(SHEET)
    bg = background(px, W, H)
    cells = find_cells(px, W, H, bg, size=16, y1=200)
    art, pals = {}, {}
    for name, idx in FRAMES.items():
        if idx >= len(cells):
            print('skip (no such cell):', name, idx)
            continue
        ox, oy = cells[idx]
        rows, pal = quantise(px, ox, oy, 16, 16, bg)
        if rows is None:
            print('skip (empty):', name)
            continue
        art[name] = rows
        pals[name] = PAL_OVERRIDE.get(name, pal)

    header = '\n'.join([
        '// NPC sprites extracted from the Oracle of Seasons NPC sheet.',
        '//',
        '// Generated by tools/rip-npcs.py — edit that, not this file.',
        '// Source sprites ripped by Trailsdegamer via spriters-resource.com;',
        "// the original artwork is Nintendo's. This is fan-work art only.",
        '//',
        '// Each sprite carries its own four colours, quantised light to dark, so',
        '// the palettes below are registered at load time rather than reusing the',
        '// hand-authored set. Farore is a palette swap: the sheet has no oracle.',
    ])
    emit_module('src/data/sprites-npcs.js', header, art, pals,
                'NPC_ART', 'installNpcSprites', 'npc')
    print('emitted', len(art), 'NPC sprites')


if __name__ == '__main__':
    main()
