#!/usr/bin/env python3
"""Extract the healing fairy from the Oracle of Seasons fairy sheet.

Sprites ripped by Mister Mike via spriters-resource.com; the original artwork is
Nintendo's. Fan-work use only. Credit requested by the ripper and given here and
in the generated module's header.

WHY THIS EXISTS. `p_fairy` was hand-drawn, and it was the one sprite in
src/data/sprites-world.js that actually broke ART-DIRECTION's outline rule:
eight body pixels along the wings' inner edges touched bare air. S35 closed
those by hand as a stopgap and said in the same breath that the real fix was
extraction, because this sheet has been sitting in assets/sheets/ unused since
it was added. This is that fix. The hand-drawn fairy is gone.

THE SHEET IS TWO HALVES and the right one is the artwork. The left half is the
same sprites through the GBC's LCD ramp — washed out — and a sprite taken from
it will not sit beside anything else extracted in this project. See
assets/sheets/README.md. The fairy row starts at x=157 on the right half and at
x=1 on the left; picking 1 instead of 157 is the mistake this note exists to
stop.

FOUR COLOURS, TWO FRAMES EACH, on 16x16 white plates at y=28:

    x=157/174  red     the healing fairy — the one this game uses
    x=191/208  orange
    x=225/242  blue
    x=259/276  green

Only the red pair is taken, because only the red pair is used: a sprite nobody
draws is a name `tools/validate.mjs` reports as unreachable, and the roster is
supposed to be the game's. The other three are recorded above rather than
extracted, the same way rip-hud.py records the magic ring's cell — if a fairy
of another colour is ever wanted, the coordinates are here and no one has to
find them again.

The two frames are the wing beat: wings up, wings out. They differ by well over
the three pixels ART-DIRECTION asks of a two-frame cycle.

Regenerate with:  python3 tools/rip-fairies.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from ripkit import load, emit_module

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHEET = os.path.join(ROOT, 'assets', 'sheets', 'oracle-seasons-fairies.png')
OUT = os.path.join(ROOT, 'src', 'data', 'sprites-fairies.js')

# The plates on this sheet are WHITE, not the tan of the HUD/gear sheet and not
# the green of the field around them. Passing the green would leave a white box
# baked round the fairy.
PLATE = (255, 255, 255)

CELLS = {
    'p_fairy':   (157, 28),   # wings up
    'p_fairy_1': (174, 28),   # wings out
}
SIZE = 16


def lum(c):
    return 0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2]


def quantise_exact(px, ox, oy, w, h, bg):
    """Map a cell's colours to indices directly, with no nearest-colour search.

    Lifted from tools/rip-hud.py, deliberately rather than shared: ripkit's own
    `quantise` picks an index by scanning for the smallest squared distance and
    keeps the first minimum, so when it pads a short palette by repeating a
    colour several indices tie at zero and which one wins is not pinned down.
    That makes the rip unstable run to run, and check-tilesets asserts these
    files regenerate byte-identically. Here the kept colours have a total order
    and every pixel is a direct lookup.

    PLATE ENCLOSED BY THE SPRITE'S OWN OUTLINE IS ARTWORK. Only plate reachable
    from the edge of the cell is erased — the fairy's body is a pale disc that
    would be punched straight through by a blanket "every white pixel is
    transparent" rule (docs/HANDOFF.md warns about exactly this).
    """
    outside = set()
    stack = [(x, 0) for x in range(w)] + [(x, h - 1) for x in range(w)] \
        + [(0, y) for y in range(h)] + [(w - 1, y) for y in range(h)]
    stack = [q for q in stack if px[ox + q[0], oy + q[1]] == bg]
    outside.update(stack)
    while stack:
        cx, cy = stack.pop()
        for nx, ny in ((cx + 1, cy), (cx - 1, cy), (cx, cy + 1), (cx, cy - 1)):
            if 0 <= nx < w and 0 <= ny < h and (nx, ny) not in outside \
                    and px[ox + nx, oy + ny] == bg:
                outside.add((nx, ny))
                stack.append((nx, ny))
    seen = {}
    for y in range(h):
        for x in range(w):
            if (x, y) in outside:
                continue
            p = px[ox + x, oy + y]
            seen[p] = seen.get(p, 0) + 1
    cols = sorted(seen, key=lambda c: (-lum(c), c))[:4]
    idx = {c: i for i, c in enumerate(cols)}
    pal = list(cols)
    while len(pal) < 4:
        pal.append(pal[-1])
    rows = []
    for y in range(h):
        rows.append(''.join(
            '.' if (x, y) in outside else str(idx[px[ox + x, oy + y]])
            for x in range(w)))
    return rows, ['#%02x%02x%02x' % c for c in pal]


HEADER = """// GENERATED by tools/rip-fairies.py — do not hand-edit.
//
// The healing fairy, extracted from assets/sheets/oracle-seasons-fairies.png
// (the "True Colors" half; see the ripper and assets/sheets/README.md). Sprites
// ripped by Mister Mike via spriters-resource.com; original artwork Nintendo's.
// Fan-work use only, credit given as the ripper asks.
//
// Two frames, the wing beat. This pack installs AFTER sprites-world.js in
// src/data/index.js and takes the `p_fairy` name from it, which is how
// sprites-npcs.js already beats the hand-drawn NPCs — extracted art wins, per
// docs/ART-DIRECTION.md rule 1.
//
// Each sprite binds its own palette, so draw sites must NOT pass one: art.js
// resolves `palName || d.pal` and an explicit palette would override the
// colours taken off the cartridge."""


def main():
    im, px, W, H = load(SHEET)
    art, pals = {}, {}
    for name, (x, y) in CELLS.items():
        rows, pal = quantise_exact(px, x, y, SIZE, SIZE, PLATE)
        art[name] = rows
        pals[name] = pal
    emit_module(OUT, HEADER, art, pals, 'FAIRY_ART', 'installFairies', 'magic')
    print('rip-fairies: %d sprite(s) -> %s' % (len(art), os.path.relpath(OUT, ROOT)))


if __name__ == '__main__':
    main()
