#!/usr/bin/env python3
"""Extract the Maku Tree's grove from the Oracle of Seasons Maku Tree sheet.

Sprites ripped by Mister Mike via spriters-resource.com; the original artwork is
Nintendo's. Fan-work use only. Credit requested by the ripper and given here and
in the generated module's header.

Regenerate with:  python3 tools/rip-maku.py

WHY THIS EXISTS. The Maku Tree was a 16x16 hand-drawn sprite standing in an
empty stone room, while `assets/sheets/oracle-seasons-maku-tree.png` sat unused
holding the whole grove: every panel on it is one full 160x128 screen — ten
cells by eight, exactly this game's room size — of the Seasons Maku Tree in its
clearing, in a different expression each.

THE SHEET IS TWO HALVES and the right one is the artwork: at x=1298 on, mean
luminance 93 and saturation 0.93 against the left half's 116 / 0.63 (the LCD
simulation). Panels sit at x = 1298 + 161n, y = 210 + 129m.

A CELL HERE IS NOT ONE FOUR-COLOUR TILE. The Game Boy Color gives every 8x8
quarter of a 16x16 cell its own palette, and the grove uses that: a cell where
a root crosses the grass carries up to nine colours. But the panel's eleven
colours fall into three clean ramps, and each is exactly four (or fewer):

    grass   #80f800 #00a028 #004840 #001800   the clearing and the wood round it
    bark    #e8b848 #b06000 #603000 #000000   the trunk and its roots
    face    #f8d088 #ff7b08 #10ad42 (#000000) the eyes, the nose and the leaf

So each cell becomes up to two stacked tiles — the grass, with holes where the
bark is, drawn underneath; the bark, with holes where the grass is, drawn on
top — and the face, which on the cartridge is a sprite over the trunk, is a
64x48 sprite the Maku Tree entity draws. Nothing is re-coloured or merged:
every pixel of the panel lands in exactly one layer, in its own colour.

What each cell DOES (solid, the way out) is design, and is declared in
src/data/tiles-core.js beside the tiledefs, not here.
"""
import os
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("rip-maku: needs Pillow — run `pip install pillow`")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHEET = os.path.join(ROOT, 'assets', 'sheets', 'oracle-seasons-maku-tree.png')
OUT = os.path.join(ROOT, 'src', 'data', 'tiles-maku.js')

# The first panel of the true-colour half: the tree at rest, eyes lowered.
PANEL = (1298, 210)
W, H = 10, 8

RAMPS = {
    'makuGrass': [(128, 248, 0), (0, 160, 40), (0, 72, 64), (0, 24, 0)],
    'makuBark':  [(232, 184, 72), (176, 96, 0), (96, 48, 0), (0, 0, 0)],
    'makuFace':  [(248, 208, 136), (255, 123, 8), (16, 173, 66), (0, 0, 0)],
}
# Black belongs to the bark: the face's own outline is drawn in the trunk.
LAYER_OF = {}
for name in ('makuGrass', 'makuFace', 'makuBark'):
    for c in RAMPS[name]:
        LAYER_OF.setdefault(c, name)
LAYER_OF[(0, 0, 0)] = 'makuBark'

# The face sprite's window, in cells: the eyes, the nose and the leaf.
FACE = (3, 0, 4, 3)


def hexc(c):
    return '#%02x%02x%02x' % c


def layer_grid(px, x0, y0, w, h, ramp):
    idx = {c: str(i) for i, c in enumerate(RAMPS[ramp])}
    rows = []
    for y in range(h):
        row = ''
        for x in range(w):
            c = px[x0 + x, y0 + y]
            if c not in LAYER_OF:
                sys.exit('rip-maku: colour %s at %d,%d is in no ramp' % (hexc(c), x0 + x, y0 + y))
            row += idx[c] if LAYER_OF[c] == ramp else '.'
        rows.append(row)
    return rows


def main():
    im = Image.open(SHEET).convert('RGB')
    px = im.load()
    X, Y = PANEL
    tiles, cells = [], []
    for cy in range(H):
        row = []
        for cx in range(W):
            x0, y0 = X + cx * 16, Y + cy * 16
            grass = layer_grid(px, x0, y0, 16, 16, 'makuGrass')
            bark = layer_grid(px, x0, y0, 16, 16, 'makuBark')
            has_g = any(ch != '.' for r in grass for ch in r)
            has_b = any(ch != '.' for r in bark for ch in r)
            base = top = None
            if has_g:
                base = 'makuG_%d_%d' % (cx, cy)
                tiles.append((base, 'makuGrass', grass, x0, y0))
            if has_b:
                top = 'makuB_%d_%d' % (cx, cy)
                tiles.append((top, 'makuBark', bark, x0, y0))
            # A cell entirely under the face sprite would have neither.
            row.append((top or base, base if top else None))
        cells.append(row)

    fx, fy, fw, fh = FACE
    face = layer_grid(px, X + fx * 16, Y + fy * 16, fw * 16, fh * 16, 'makuFace')

    lines = [
        '// GENERATED by tools/rip-maku.py — do not edit by hand.',
        '//',
        '// The Maku Tree\'s grove, from assets/sheets/oracle-seasons-maku-tree.png',
        '// (the true-colour half, panel at %d,%d). Sprites ripped by Mister Mike via' % PANEL,
        '// spriters-resource.com; the original artwork is Nintendo\'s. Fan-work only.',
        '//',
        '// Every cell is up to two stacked tiles — grass beneath, bark on top — and',
        '// the face is a sprite the Maku Tree draws over the trunk. See the ripper.',
        '',
        "import { sprites } from '../gfx/art.js';",
        '',
        'export const MAKU_PALETTES = {',
    ]
    for name, ramp in RAMPS.items():
        lines.append('  %s: [%s],' % (name, ', '.join("'%s'" % hexc(c) for c in ramp)))
    lines += ['};', '', '// extracted — every tile below is cut straight off the panel named above.',
              'export const MAKU_TILE_ART = {']
    for name, pal, grid, x0, y0 in tiles:
        lines.append('  // %s layer @ %d,%d' % (pal, x0, y0))
        lines.append('  %s: `' % name)
        lines.extend('    ' + r for r in grid[:-1])
        lines.append('    ' + grid[-1] + '`,')
    lines += ['};', '',
              '// The grove, cell by cell: [the tile drawn, the grass drawn under it or null].',
              'export const MAKU_GROVE = [']
    for row in cells:
        lines.append('  [%s],' % ', '.join(
            "['%s', %s]" % (t, "'%s'" % b if b else 'null') for t, b in row))
    lines += ['];', '',
              '// Where the face sits, in pixels from the grove\'s top-left.',
              'export const MAKU_FACE_AT = [%d, %d];' % (fx * 16, fy * 16), '',
              'export const MAKU_SPRITE_ART = {',
              '  // extracted — the eyes, nose and leaf, the sprite layer over the trunk.',
              "  maku_face: { pal: 'makuFace', art: `"]
    lines.extend('    ' + r for r in face[:-1])
    lines.append('    ' + face[-1] + '` },')
    lines += ['};', '',
              'export function installMakuSprites() {',
              "  sprites.add(MAKU_SPRITE_ART, 'makuFace');",
              '}', '']
    with open(OUT, 'w') as f:
        f.write('\n'.join(lines))
    print('emitted %d grove tiles and the face -> %s' % (len(tiles), OUT))


if __name__ == '__main__':
    main()
