#!/usr/bin/env python3
"""Extract background terrain tiles from the reference sheets.

  python3 tools/rip-terrain.py          # rewrite src/data/tiles-terrain.js

`docs/ART-DIRECTION.md` names `assets/sheets/custom-oracle-style-overworld.png`
and `assets/sheets/oracle-seasons-dungeon-backgrounds.png` the references for
overworld and dungeon terrain, and says to extract from them rather than
approximate. Both sheets are assembled *maps*, not tile palettes, so there is no
cell grid to walk the way `rip-enemies.py` walks the enemy sheet — each map
block sits at its own origin. `PICKS` below therefore records one hand-verified
16x16 source rectangle per tile.

How each rectangle was found, so it can be redone for a tile not listed here:

  A ground tile is the 16x16 window that repeats at +16 in x *and* +16 in y. A
  window that passes that test is both correctly phased and seamless by
  construction, which is exactly the property `docs/ART-DIRECTION.md` demands of
  terrain. Scanning a region for windows that pass, collapsing the 256 cyclic
  phase shifts of each hit onto one key and ranking by area covered hands back
  the region's tile set. The scratch script that does it is not committed; the
  paragraph above is the whole algorithm.

What this tool deliberately does NOT do:

  * It does not touch the palettes. Every tile here keeps the palette its
    definition in `tiles-core.js` already binds, so the palette-swap variants
    (`grassDark`, `saltFlat`, `iceFloor`, `rockFloorRust`, ...) keep working and
    the game's colour scheme does not shift under the extracted enemy sprites.
    The four source colours are emitted alongside as `*_SRC` for reference.
  * It does not extract animated tiles. The sheets are static maps and hold no
    second frame, so water stays hand-drawn.

Source sheets are Nintendo's artwork (dungeon backgrounds) and a fan-made
Oracle-style tileset; see `assets/sheets/README.md` for ripper credit.
"""

import os
import sys
from collections import Counter

try:
    from PIL import Image
except ImportError:
    sys.exit("rip-terrain: needs Pillow — run `pip install pillow`")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OW = os.path.join(ROOT, 'assets/sheets/custom-oracle-style-overworld.png')
DG = os.path.join(ROOT, 'assets/sheets/oracle-seasons-dungeon-backgrounds.png')
OUT = os.path.join(ROOT, 'src/data/tiles-terrain.js')

# art name -> (sheet, x, y, note). The note is what the tile is on the sheet,
# which is worth recording because the coordinates alone say nothing.
PICKS = [
    ('grassTuft',   OW, 1611,  307, 'grass with scattered tufts'),
    ('tallgrass',   OW,  886, 1049, 'tall blades, the cuttable kind'),
    ('sand',        OW, 1788,   65, 'dry sand, sparse grain'),
    ('sandWet',     OW, 1933,   81, 'damp sand, denser grain'),
    ('sandRipple',  OW,  484,    1, 'wind-rippled dune'),
    ('mud',         OW, 2206,  154, 'churned bog'),
    ('rockFloor',   OW,  645, 1549, 'cobbled paving'),
    ('dFloor',      DG,  547,   42, 'dungeon floor, mottled flagstone'),
    ('dWall',       DG,  483,   26, 'dungeon wall run, lit top and hatched base'),
]


def lum(c):
    return 0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2]


def quantise(block):
    """16x16 RGB -> (grid of 0-3, four source colours lightest first).

    Deliberately not `ripkit.quantise`: that pads a short palette by repeating
    its last colour and then picks indices by nearest-distance search, which
    ties and is not reproducible (see docs/HANDOFF.md). Here the four kept
    colours are ranked by a total order and every pixel is a direct lookup, so
    the output is byte-identical run to run.
    """
    cnt = Counter(p for row in block for p in row)
    # Ties broken on the RGB tuple so the choice does not depend on dict order.
    ranked = sorted(cnt.items(), key=lambda kv: (-kv[1], kv[0]))
    keep = sorted((c for c, _ in ranked[:4]), key=lambda c: (-lum(c), c))
    remap = {c: min(keep, key=lambda k: ((lum(k) - lum(c)) ** 2, k)) for c in cnt}
    idx = {c: i for i, c in enumerate(keep)}
    grid = [''.join(str(idx[remap[p]]) for p in row) for row in block]
    return grid, keep


def hexc(c):
    return '#%02x%02x%02x' % c


def main():
    sheets = {}
    arts, pals, dropped = [], [], []
    for name, path, x, y, note in PICKS:
        im = sheets.get(path)
        if im is None:
            im = sheets[path] = Image.open(path).convert('RGB')
        block = [[im.getpixel((x + cx, y + cy)) for cx in range(16)] for cy in range(16)]
        before = len({p for row in block for p in row})
        grid, keep = quantise(block)
        if before > 4:
            dropped.append((name, before))
        arts.append((name, note, os.path.basename(path), x, y, grid))
        pals.append((name, keep))

    lines = [
        '// GENERATED by tools/rip-terrain.py — do not edit by hand.',
        '//',
        '// Background terrain extracted from the reference sheets in assets/sheets/,',
        '// which docs/ART-DIRECTION.md makes the canonical source for terrain. Each',
        '// tile is a 16x16 window that repeats at +16 in both axes on its sheet, so it',
        '// is correctly phased and tiles seamlessly with itself by construction.',
        '//',
        '// These override the hand-drawn art of the same name in tiles-core.js. Only the',
        '// pixels change: every tile keeps the palette its definition there already',
        '// binds, which is what keeps the palette-swap variants (grassDark, saltFlat,',
        '// iceFloor, rockFloorRust, ...) rendering. TERRAIN_SRC_PALETTES records the',
        '// four colours each tile actually has on the sheet, for reference.',
        '',
        'export const TERRAIN_ART = {',
    ]
    for name, note, sheet, x, y, grid in arts:
        lines.append('  // %s — %s @ %d,%d' % (note, sheet, x, y))
        lines.append('  %s: `' % name)
        lines.extend('    ' + r for r in grid[:-1])
        lines.append('    ' + grid[-1] + '`,')
        lines.append('')
    lines.append('};')
    lines.append('')
    lines.append('// The source colours, lightest first — not installed, kept for reference.')
    lines.append('export const TERRAIN_SRC_PALETTES = {')
    for name, keep in pals:
        lines.append("  %s: [%s]," % (name, ', '.join("'%s'" % hexc(c) for c in keep)))
    lines.append('};')
    lines.append('')

    with open(OUT, 'w') as f:
        f.write('\n'.join(lines))
    print('emitted %d terrain tiles -> %s' % (len(arts), OUT))
    for name, n in dropped:
        print('  note: %s had %d colours on the sheet, merged down to 4' % (name, n))


if __name__ == '__main__':
    main()
