#!/usr/bin/env python3
"""Extract townsfolk sprites from the Oracle of Seasons non-human races sheet.

  python3 tools/rip-townsfolk.py        # rewrite src/data/sprites-townsfolk.js

Sprites ripped by Mister Mike, via spriters-resource.com; the original artwork
is Nintendo's. Fan-work use only.

WHY THIS SHEET, AND WHY A SECOND NPC TOOL. `tools/rip-npcs.py` walks the NPC
sheet with `find_cells`, which finds sprites by looking for islands of
non-background pixels — and that works there because the sprites sit directly on
the sheet's green. On THIS sheet every character stands on its own WHITE BOX, so
the green background is the gap between boxes and the box is what gets found: a
cell comes back as white-on-white with no transparency at all, and the sprite
draws as a white square. The fix is one line and it is why the picks below carry
their own background colour — quantise against WHITE, not against the sheet.

The rows are also not on a uniform pitch (17px here, 16 there, and the taller
kings break both), so each pick records a hand-verified origin the way
`rip-terrain.py` does rather than an index into a cell list that shifts the
moment the detector's idea of a band changes.

Their DESIGN is ours: these are Thalassia's coast people, and nothing about who
they are or what they say comes off the sheet. Only how they look does, which is
the rule in CLAUDE.md — if a sheet has it, extract it.
"""
import sys, os

sys.path.insert(0, os.path.dirname(__file__))
from ripkit import load, lum, _fill_pinholes, emit_module

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHEET = os.path.join(ROOT, 'assets/sheets/oracle-seasons-nonhuman-races.png')
OUT = os.path.join(ROOT, 'src/data/sprites-townsfolk.js')

WHITE = (255, 255, 255)

# engine sprite name -> (x, y, background, note)
#
# `_s` faces RIGHT, always: the engine mirrors it for left, and a left-facing
# frame would come out backwards. Both side frames in the source walk cycle face
# right, and the one taken here is the standing half of it.
PICKS = [
    ('npc_tidefolk_d', 815, 555, WHITE, 'bandana, facing the viewer'),
    ('npc_tidefolk_u', 832, 555, WHITE, 'the same person from behind'),
    ('npc_tidefolk_s', 849, 555, WHITE, 'in profile, facing right'),
    ('npc_tidefolk2_d', 1057, 555, WHITE, 'the red-scarf variant, front'),
    ('npc_lass_d', 918, 555, WHITE, 'young woman with a tied bow, front'),
    ('npc_lass_u', 935, 555, WHITE, 'the same, from behind'),
    ('npc_carver_d', 1070, 431, WHITE, 'a hooded figure, green cloak'),
]


def quantise_boxed(px, ox, oy, bg):
    """16x16 -> (rows of 0-3 and '.', colours lightest first).

    The box the character stands on becomes transparent, but only where it is
    reachable from the cell border. Box colour ENCLOSED by the character's own
    outline is artwork: the lass's dress is white, and a plain colour-equality
    test cuts her body out and leaves a face and a bow floating in the square.
    Flooding inward from the border is the same rule `rip-terrain.py` uses for a
    prop standing on ground, and for the same reason.
    """
    grid = [[None] * 16 for _ in range(16)]
    stack = [(i, e) for i in range(16) for e in (0, 15)]
    stack += [(e, i) for i in range(16) for e in (0, 15)]
    seen = set()
    while stack:
        cx, cy = stack.pop()
        if not (0 <= cx < 16 and 0 <= cy < 16) or (cx, cy) in seen:
            continue
        if px[ox + cx, oy + cy] != bg:
            continue
        seen.add((cx, cy))
        grid[cy][cx] = '.'
        stack += [(cx + 1, cy), (cx - 1, cy), (cx, cy + 1), (cx, cy - 1)]

    kept = sorted({px[ox + cx, oy + cy] for cy in range(16) for cx in range(16)
                   if grid[cy][cx] is None}, key=lambda c: (-lum(c), c))
    if not kept:
        return None, None
    if len(kept) > 4:
        raise SystemExit('rip-townsfolk: %d,%d has %d colours, 4 slots'
                         % (ox, oy, len(kept)))
    idx = {c: i for i, c in enumerate(kept)}
    for cy in range(16):
        for cx in range(16):
            if grid[cy][cx] is None:
                grid[cy][cx] = str(idx[px[ox + cx, oy + cy]])
    rows = _fill_pinholes([''.join(r) for r in grid])
    pal = ['#%02x%02x%02x' % c for c in kept]
    while len(pal) < 4:
        pal.append(pal[-1])
    return rows, pal


def main():
    im, px, W, H = load(SHEET)
    art, pals = {}, {}
    for name, x, y, bg, note in PICKS:
        rows, pal = quantise_boxed(px, x, y, bg)
        if rows is None:
            print('skip (empty):', name)
            continue
        art[name] = rows
        pals[name] = pal

    header = '\n'.join([
        '// Townsfolk sprites extracted from the Oracle of Seasons non-human',
        '// races sheet.',
        '//',
        '// Generated by tools/rip-townsfolk.py — edit that, not this file.',
        '// Source sprites ripped by Mister Mike via spriters-resource.com;',
        "// the original artwork is Nintendo's. This is fan-work art only.",
        '//',
        '// These are the people of Thalassia\'s coast. Who they are, what they',
        '// keep and what they say is original to this game; only how they look',
        '// comes off the sheet.',
        '//',
        '// Each sprite carries its own colours, quantised light to dark, so the',
        '// palettes below are registered at load time. The characters on this',
        '// sheet stand on white boxes rather than on the sheet background, so',
        '// each pick names WHITE as its background — see the tool.',
    ])
    emit_module(OUT, header, art, pals,
                'TOWNSFOLK_ART', 'installTownsfolkSprites', 'npc')
    print('emitted', len(art), 'townsfolk sprites')


if __name__ == '__main__':
    main()
