// Indexed full-colour images: the Seasons title, file-select, save and
// inventory screens (src/data/screens-seasons.js, generated by
// tools/rip-screens.py). Unlike a sprite, one of these is not four colours —
// a Game Boy Color screen gives every 8x8 its own palette — so each is a
// palette plus one character per pixel, painted once to a canvas and blitted
// from the cache after that. No per-pixel work happens in a draw.

import { SEASONS_SCREENS } from '../data/screens-seasons.js';

const KEYS = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
const cache = new Map();

function bake(name) {
  const s = SEASONS_SCREENS[name];
  if (!s) throw new Error(`screens: no image named ${name}`);
  const c = document.createElement('canvas');
  c.width = s.w; c.height = s.h;
  const g = c.getContext('2d');
  const img = g.createImageData(s.w, s.h);
  const rgb = s.pal.map(h => [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)]);
  for (let y = 0; y < s.h; y++) {
    const row = s.rows[y];
    for (let x = 0; x < s.w; x++) {
      const ch = row[x];
      if (ch === '.') continue;
      const c3 = rgb[KEYS.indexOf(ch)], o = (y * s.w + x) * 4;
      img.data[o] = c3[0]; img.data[o + 1] = c3[1]; img.data[o + 2] = c3[2]; img.data[o + 3] = 255;
    }
  }
  g.putImageData(img, 0, 0);
  const out = { canvas: c, w: s.w, h: s.h, y: s.y || 0 };
  cache.set(name, out);
  return out;
}

/** The baked image, for its size and its own `y` if the ripper gave one. */
export function screenImage(name) { return cache.get(name) || bake(name); }

/** Draw a screen image with its top-left at (x, y). */
export function drawScreen(ctx, name, x = 0, y = 0) {
  const s = screenImage(name);
  ctx.drawImage(s.canvas, Math.round(x), Math.round(y));
}
