// The moments the guide photographs. See capture.mjs for what `after`,
// `until` and `plus` mean. Route shots must stay in route order.
const DLG = 'g.dialogue.active && g.dialogue.chars >= g.dialogue.pageLen';
const ANCHOR_FLYING = "g.entities.some(e => e.sprite === 'o_anchor' && e.state === 'flight')";
const ANCHOR_HELD = "g.entities.some(e => e.sprite === 'o_anchor' && e.state === 'held')";
const ITEM = 'g.itemShow && g.itemShow.t < 100';
const IN = (k) => `g.room && g.mapId + ' ' + g.room.key === ${JSON.stringify(k)}`;

export const ROUTE_SHOTS = [
  // --------------------------------------------------------- the start
  // S159: the opening since S158 — washed up on the Fishing Stones with
  // nothing, Teel, Wenna in Palisade Row, the sword in the Shipwright's
  // Hollow, Farore's shrine on Tern Point, then the Maku Tree's key.
  { id: 'intro-wake', after: 0, plus: 30, whole: true },
  { id: 'intro-teel', after: 0, until: DLG, plus: 2, by: 1 },
  { id: 'intro-wenna', after: 2, until: DLG, plus: 2, by: 3 },
  { id: 'intro-gull', after: 4, plus: 0, whole: true },
  { id: 'intro-hollow', after: 7, plus: 5, whole: true },
  { id: 'intro-sword', after: 11, until: ITEM, plus: 30, by: 12 },
  { id: 'intro-tern', after: 15, plus: 0, whole: true },
  { id: 'intro-farore', after: 17, until: DLG, plus: 2, by: 18 },
  { id: 'intro-conch', after: 17, until: ITEM, plus: 30, by: 18 },
  { id: 'village', after: 23, plus: 30, whole: true },
  { id: 'village-hud', after: 23, plus: 30 },
  { id: 'intro-maku', after: 25, until: DLG, plus: 2, by: 26 },
  { id: 'village-conch', after: 42, until: 'g.tide.busy', plus: 10, by: 43 },
  { id: 'ow-grotto', after: 53, plus: 0, whole: true },
  // --------------------------------------------------------------- D1
  { id: 'd1-enter', after: 55, until: IN('d1 0,3,7'), plus: 70, whole: true },
  { id: 'd1-mouth-conch', after: 58, until: 'g.tide.busy', plus: 8, by: 59, whole: true },
  { id: 'd1-mouth-low', after: 60, whole: true },
  { id: 'd1-drink', after: 61, plus: 20, whole: true },
  { id: 'd1-hall', after: 65, plus: 30, whole: true },
  { id: 'd1-hall-push1', after: 69, plus: 40, whole: true },
  { id: 'd1-hall-push2', after: 71, plus: 60, whole: true },
  { id: 'd1-hall-fairy', after: 73, plus: 10, whole: true },
  { id: 'd1-mapalcove', after: 75, plus: 20, whole: true },
  { id: 'd1-chart', after: 78, plus: 10, whole: true },
  { id: 'd1-chart-open', after: 83, until: 'g.dialogue.active', plus: 20 },
  { id: 'd1-gallery', after: 86, plus: 10, whole: true },
  { id: 'd1-crabpit', after: 90, plus: 30, whole: true },
  { id: 'd1-crabpit-key', after: 92, until: DLG, plus: 2, whole: true },
  { id: 'd1-switch', after: 95, plus: 10, whole: true },
  { id: 'd1-switch-done', after: 101, until: DLG, plus: 2, whole: true },
  { id: 'd1-gallery-door', after: 108, until: DLG, plus: 1, whole: true },
  { id: 'd1-stair', after: 111, plus: 30, whole: true },
  
  { id: 'd1-sluicegate', after: 119, plus: 20, whole: true },
  { id: 'd1-anchor-get', after: 122, until: 'g.dialogue.active', plus: 20 },
  { id: 'd1-anchor-menu', after: 125, until: "g.mode === 'menu'", plus: 60 },
  { id: 'd1-pipe', after: 127, plus: 10, whole: true },
  { id: 'd1-pipe-throw', after: 127, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-pipe-held', after: 128, plus: 0, whole: true },
  { id: 'd1-pipe-mid', after: 129, plus: 30, whole: true },
  { id: 'd1-chamber', after: 131, plus: 10, whole: true },
  { id: 'd1-chamber-low', after: 132, plus: 5, whole: true },
  { id: 'd1-race', after: 135, plus: 10, whole: true },
  { id: 'd1-race-throw', after: 136, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-race-mid', after: 138, plus: 30, whole: true },
  { id: 'd1-keyvault', after: 140, plus: 10, whole: true },
  { id: 'd1-keyvault-key', after: 146, until: 'g.dialogue.active', plus: 20 },
  { id: 'd1-den', after: 159, plus: 10, whole: true },
  { id: 'd1-den-fight1', after: 160, plus: 120, whole: true },
  { id: 'd1-den-fight2', after: 160, plus: 30 },
  { id: 'd1-den-fight3', after: 160, plus: 180 },
  { id: 'd1-den-piece', after: 162, plus: 10, whole: true },
  { id: 'd1-den-door', after: 166, plus: 2 },
  { id: 'd1-gauges', after: 169, plus: 10, whole: true },
  { id: 'd1-gauges-low', after: 171, plus: 5, whole: true },
  { id: 'd1-gauges-throw', after: 171, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-gauges-open', after: 173, until: DLG, plus: 2, whole: true },
  { id: 'd1-gauges-piece', after: 175, plus: 12 },
  { id: 'd1-gauges-stair', after: 177, plus: 60, whole: true },
  { id: 'd1-stair2', after: 178, plus: 10, whole: true },
  { id: 'd1-sluice', after: 190, plus: 10, whole: true },
  { id: 'd1-sluice-throw1', after: 190, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-sluice-low', after: 192, plus: 5, whole: true },
  { id: 'd1-sluice-throw2', after: 193, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-sluice-mid', after: 195, plus: 30, whole: true },
  { id: 'd1-turn', after: 197, plus: 10, whole: true },
  { id: 'd1-drip', after: 199, plus: 10, whole: true },
  { id: 'd1-drip-throw', after: 204, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-drip-open', after: 206, plus: 0, whole: true },
  { id: 'd1-bkvault', after: 209, plus: 10, whole: true },
  { id: 'd1-bosskey', after: 213, plus: 30 },
  { id: 'd1-bossdoor', after: 226, plus: 2, whole: true },
  { id: 'd1-boss-intro', after: 229, plus: 40, whole: true },
  { id: 'd1-boss-a', after: 230, plus: 40 },
  { id: 'd1-boss-b', after: 230, plus: 70 },
  { id: 'd1-boss-c', after: 230, plus: 70 },
  { id: 'd1-boss-d', after: 230, plus: 70 },
  { id: 'd1-boss-e', after: 230, plus: 70 },
  { id: 'd1-boss-f', after: 230, plus: 70 },
  { id: 'd1-boss-g', after: 230, plus: 70 },
  { id: 'd1-boss-h', after: 230, plus: 70 },
  { id: 'd1-boss-won', after: 232, plus: 0, whole: true },
  { id: 'd1-essence', after: 233, until: DLG, plus: 2, by: 236 },
  { id: 'end-d1', after: 239 },
  { id: 'ow2-shop', after: 245, plus: 2 },
  { id: 'ow2-sandpiper', after: 264, plus: 0, whole: true },
  { id: 'd2-mouth', after: 275, plus: 20, whole: true },
  { id: 'd2-landing', after: 277, plus: 5, whole: true },
  { id: 'd2-landing-fairy', after: 278, plus: 20, whole: true },
  { id: 'ow2-shellflats', after: 291, plus: 5, whole: true },
  { id: 'd2-rising', after: 304, plus: 5, whole: true },
  { id: 'd2-rising-done', after: 309, plus: 20, whole: true },
  { id: 'd2-coil', after: 319, plus: 0, whole: true },
  { id: 'd2-sealed', after: 323, plus: 5, whole: true },
  { id: 'd2-lens-get', after: 326, plus: 30 },
  { id: 'd2-glass', after: 330, plus: 60, whole: true },
  { id: 'd2-glass-lens', after: 330, plus: 0, until: 'g.player && g.player.lensT > 0', by: 331 },
  { id: 'd2-glass-piece', after: 332, plus: 5, whole: true },
  { id: 'd2-fork1', after: 335, plus: 5, whole: true },
  { id: 'd2-fork1-valve', after: 339, plus: 30, whole: true },
  { id: 'd2-reefguard', after: 342, plus: 60, whole: true },
  { id: 'd2-reefguard-fight', after: 342, plus: 200 },
  { id: 'd2-reefguard-key', after: 351, plus: 5, whole: true },
  { id: 'd2-bombvault', after: 353, plus: 5, whole: true },
  { id: 'd2-bombs-get', after: 356, plus: 30 },
  { id: 'd2-whelk', after: 359, plus: 5, whole: true },
  { id: 'd2-ascent', after: 364, plus: 5, whole: true },
  { id: 'd2-soundfork', after: 370, plus: 5, whole: true },
  { id: 'd2-soundfork-valve', after: 375, plus: 30, whole: true },
  { id: 'd2-bosskey', after: 377, plus: 5, whole: true },
  { id: 'd2-bosskey-get', after: 380, plus: 30 },
  { id: 'd2-bossdoor', after: 390, plus: 5, whole: true },
  { id: 'd2-boss-intro', after: 394, plus: 60, whole: true },
  { id: 'd2-boss-a', after: 394, plus: 300 },
  { id: 'd2-boss-b', after: 394, plus: 300 },
  { id: 'd2-boss-c', after: 394, plus: 400 },
  { id: 'd2-boss-d', after: 394, plus: 500 },
  { id: 'd2-essence', after: 397, plus: 0, whole: true },
  { id: 'ow3-causeway', after: 433, plus: 5, whole: true },
  { id: 'ow3-bomb', after: 437, plus: 30, whole: true },
  { id: 'ow3-open', after: 439, plus: 0, whole: true },
  { id: 'd3-mouth', after: 444, plus: 10, whole: true },
  { id: 'd3-nave', after: 446, plus: 5, whole: true },
  { id: 'd3-mapcell', after: 453, plus: 5, whole: true },
  { id: 'd3-sluice', after: 455, plus: 5, whole: true },
  { id: 'd3-sluice-done', after: 459, plus: 5, whole: true },
  { id: 'd3-weir', after: 464, plus: 5, whole: true },
  { id: 'd3-silt', after: 468, plus: 5, whole: true },
  { id: 'd3-reed', after: 474, plus: 5, whole: true },
  { id: 'd3-cistern', after: 483, plus: 5, whole: true },
  { id: 'd3-cleats-get', after: 486, plus: 30 },
  { id: 'd3-cistern-sink', after: 491, plus: 20, whole: true },
  { id: 'd3-undertow', after: 492, plus: 30, whole: true },
  { id: 'd3-vestry', after: 495, plus: 5, whole: true },
  { id: 'd3-vestry-done', after: 500, plus: 5, whole: true },
  { id: 'd3-drain-gallery', after: 508, plus: 5, whole: true },
  { id: 'd3-bosskey-get', after: 512, plus: 30 },
  { id: 'd3-bogmaw', after: 515, plus: 5, whole: true },
  { id: 'd3-bogmaw-fight', after: 517, plus: 200 },
  { id: 'd3-roof', after: 522, plus: 5, whole: true },
  { id: 'd3-drain', after: 530, plus: 5, whole: true },
  { id: 'd3-eelhall', after: 541, plus: 5, whole: true },
  { id: 'd3-eelvault', after: 556, plus: 5, whole: true },
  { id: 'd3-soundpool', after: 577, plus: 5, whole: true },
  { id: 'd3-soundpool-sink', after: 581, plus: 60, whole: true },
  { id: 'd3-weights', after: 587, plus: 5, whole: true },
  { id: 'd3-weights-push', after: 592, plus: 5, whole: true },
  { id: 'd3-weights-plate', after: 597, plus: 20, whole: true },
  { id: 'd3-kelp', after: 614, plus: 5, whole: true },
  { id: 'd3-kelp-sink', after: 620, plus: 40, whole: true },
  { id: 'd3-lockgallery', after: 623, plus: 5, whole: true },
  { id: 'd3-bossdoor', after: 631, plus: 5, whole: true },
  { id: 'd3-boss-intro', after: 633, plus: 60, whole: true },
  { id: 'd3-boss-a', after: 633, plus: 400 },
  { id: 'd3-boss-b', after: 633, plus: 600 },
  { id: 'd3-boss-c', after: 633, plus: 900 },
  { id: 'ow4-deepcut', after: 670, plus: 5, whole: true },
  { id: 'ow4-bomb', after: 675, plus: 30, whole: true },
  { id: 'ow4-cistmouth', after: 684, plus: 5, whole: true },
  { id: 'd4-head', after: 687, plus: 20, whole: true },
  { id: 'd4-basin', after: 691, plus: 5, whole: true },
  { id: 'd4-weir', after: 695, plus: 5, whole: true },
  { id: 'd4-floor', after: 702, plus: 5, whole: true },
  { id: 'd4-floor-push', after: 705, plus: 5, whole: true },
  { id: 'd4-floor-plate', after: 708, plus: 5, whole: true },
  { id: 'd4-winch', after: 713, plus: 5, whole: true },
  { id: 'd4-bellowsvault', after: 719, plus: 5, whole: true },
  { id: 'd4-bellows-get', after: 722, plus: 30 },
  { id: 'd4-loft', after: 726, plus: 5, whole: true },
  { id: 'd4-loft-blow', after: 730, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 732 },
  { id: 'd4-ebb', after: 736, plus: 5, whole: true },
  { id: 'd4-ebb-high', after: 739, plus: 5, whole: true },
  { id: 'd4-ebb-blow', after: 741, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 743 },
  { id: 'd4-spillvault', after: 746, plus: 5, whole: true },
  { id: 'd4-dsill', after: 757, plus: 5, whole: true },
  { id: 'd4-dsill-blow', after: 760, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 763 },
  { id: 'd4-gauge', after: 764, plus: 5, whole: true },
  { id: 'd4-gauge-blow', after: 767, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 770 },
  { id: 'd4-overlook', after: 774, plus: 5, whole: true },
  { id: 'd4-stair', after: 779, plus: 5, whole: true },
  { id: 'd4-race', after: 786, plus: 5, whole: true },
  { id: 'd4-race-blow1', after: 788, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 791 },
  { id: 'd4-race-blow2', after: 792, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 794 },
  { id: 'd4-ironknight', after: 796, plus: 60, whole: true },
  { id: 'd4-ironknight-fight', after: 797, plus: 300 },
  { id: 'd4-cliffwalk', after: 802, plus: 5, whole: true },
  { id: 'd4-crossed', after: 810, plus: 5, whole: true },
  { id: 'd4-crossed-blow1', after: 813, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 816 },
  { id: 'd4-crossed-blow2', after: 818, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 820 },
  { id: 'd4-crossed-key', after: 822, plus: 5, whole: true },
  { id: 'd4-eastlook', after: 825, plus: 5, whole: true },
  { id: 'd4-gate', after: 832, plus: 5, whole: true },
  { id: 'd4-boss-intro', after: 840, plus: 90, whole: true },
  { id: 'd4-boss-a', after: 841, plus: 600 },
  { id: 'd4-boss-b', after: 841, plus: 800 },
  { id: 'd4-boss-c', after: 841, plus: 1200 },
  { id: 'ow5-noble', after: 873, plus: 40 },
  { id: 'ow5-shrinemouth', after: 883, plus: 5, whole: true },
  { id: 'd5-landing', after: 889, plus: 5, whole: true },
  { id: 'd5-silt', after: 892, plus: 5, whole: true },
  { id: 'd5-bracken', after: 896, plus: 5, whole: true },
  { id: 'd5-chartnave', after: 901, plus: 5, whole: true },
  { id: 'd5-cloister', after: 910, plus: 5, whole: true },
  { id: 'd5-cloister-high', after: 912, plus: 5, whole: true },
  { id: 'd5-thicket', after: 917, plus: 5, whole: true },
  { id: 'd5-bower', after: 926, plus: 5, whole: true },
  { id: 'd5-bower-blow', after: 928, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 931 },
  { id: 'd5-grove', after: 936, plus: 5, whole: true },
  { id: 'd5-rootbound', after: 943, plus: 5, whole: true },
  { id: 'd5-sbracken', after: 945, plus: 5, whole: true },
  { id: 'd5-warden', after: 961, plus: 5, whole: true },
  { id: 'd5-seedvault', after: 969, plus: 5, whole: true },
  { id: 'd5-seed-get', after: 973, plus: 30 },
  { id: 'd5-stake1', after: 977, plus: 5, whole: true },
  { id: 'd5-stake1-high', after: 979, plus: 5, whole: true },
  { id: 'd5-stake1-throw', after: 979, plus: 0, whole: true, until: "g.entities.some(e => e.constructor && /seed/i.test(e.constructor.name))", by: 981 },
  { id: 'd5-stake1-low', after: 981, plus: 60, whole: true },
  { id: 'd5-stake1-cut', after: 985, plus: 5, whole: true },
  { id: 'd5-bolewalk', after: 989, plus: 5, whole: true },
  { id: 'd5-bolewalk-low', after: 995, plus: 60, whole: true },
  { id: 'd5-snave', after: 1003, plus: 5, whole: true },
  { id: 'd5-snave-low', after: 1008, plus: 60, whole: true },
  { id: 'd5-knotted', after: 1025, plus: 5, whole: true },
  { id: 'd5-knotted-low', after: 1032, plus: 60, whole: true },
  { id: 'd5-knotted-2', after: 1033, plus: 60, whole: true },
  { id: 'd5-rootford', after: 1041, plus: 5, whole: true },
  { id: 'd5-rootford-low', after: 1047, plus: 40, whole: true },
  { id: 'd5-rootford-pushed', after: 1054, plus: 5, whole: true },
  { id: 'd5-crossing', after: 1080, plus: 5, whole: true },
  { id: 'd5-longford', after: 1084, plus: 5, whole: true },
  { id: 'd5-longford-low', after: 1090, plus: 60, whole: true },
  { id: 'd5-thornvine', after: 1101, plus: 60, whole: true },
  { id: 'd5-thornvine-fight', after: 1101, plus: 240 },
  { id: 'd5-shrineford', after: 1108, plus: 5, whole: true },
  { id: 'd5-shrineford-2', after: 1113, plus: 60, whole: true },
  { id: 'd5-arch', after: 1128, plus: 5, whole: true },
  { id: 'd5-boss-intro', after: 1135, plus: 90, whole: true },
  { id: 'd5-boss-a', after: 1136, plus: 500 },
  { id: 'd5-boss-b', after: 1136, plus: 800 },
  { id: 'd5-boss-c', after: 1136, plus: 1200 },
  { id: 'ow6-maku', after: 1298, plus: 5, whole: true },
  { id: 'ow6-rod', after: 1299, plus: 5 },
  { id: 'ow6-gate', after: 1329, plus: 5, whole: true },
  { id: 'd6-door', after: 1332, plus: 10, whole: true },
  { id: 'd6-bone', after: 1338, plus: 5, whole: true },
  { id: 'd6-drain', after: 1343, plus: 5, whole: true },
  { id: 'd6-drain-done', after: 1347, plus: 5, whole: true },
  { id: 'd6-kiln', after: 1353, plus: 5, whole: true },
  { id: 'd6-kiln-lit', after: 1371, plus: 60, whole: true },
  { id: 'd6-crypt', after: 1377, plus: 5, whole: true },
  { id: 'd6-crypt-blow', after: 1379, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 1381 },
  { id: 'd6-heights', after: 1383, plus: 5, whole: true },
  { id: 'd6-lock', after: 1389, plus: 5, whole: true },
  { id: 'd6-dredgevault', after: 1404, plus: 5, whole: true },
  { id: 'd6-dredge-get', after: 1407, plus: 30 },
  { id: 'd6-slack', after: 1413, plus: 5, whole: true },
  { id: 'd6-slack-cast', after: 1414, plus: 0, whole: true, until: "g.entities.some(e => /dredge|lure|hook/i.test(e.constructor.name))", by: 1416 },
  { id: 'd6-draw', after: 1417, plus: 5, whole: true },
  { id: 'd6-draw-cast', after: 1422, plus: 0, whole: true, until: "g.entities.some(e => /dredge|lure|hook/i.test(e.constructor.name))", by: 1424 },
  { id: 'd6-tally', after: 1429, plus: 5, whole: true },
  { id: 'd6-hauling', after: 1444, plus: 5, whole: true },
  { id: 'd6-upper', after: 1470, plus: 5, whole: true },
  { id: 'd6-tideshade', after: 1474, plus: 60, whole: true },
  { id: 'd6-tideshade-fight', after: 1474, plus: 300 },
  { id: 'd6-mermaid', after: 1479, plus: 5, whole: true },
  { id: 'd6-arches', after: 1486, plus: 5, whole: true },
  { id: 'd6-arches-lens', after: 1489, plus: 0, until: 'g.player && g.player.lensHeld', by: 1491 },
  { id: 'd6-shade', after: 1510, plus: 5, whole: true },
  { id: 'd6-colonnade', after: 1518, plus: 5, whole: true },
  { id: 'd6-colonnade-rod', after: 1520, plus: 5, whole: true },
  { id: 'd6-stand', after: 1532, plus: 5, whole: true },
  { id: 'd6-crossing', after: 1537, plus: 5, whole: true },
  { id: 'd6-bar', after: 1538, plus: 5, whole: true },
  { id: 'd6-sill', after: 1561, plus: 5, whole: true },
  { id: 'd6-gate', after: 1581, plus: 5, whole: true },
  { id: 'd6-shafts', after: 1587, plus: 5, whole: true },
  { id: 'd6-shafts-cast1', after: 1588, plus: 0, whole: true, until: "g.entities.some(e => /dredge|lure|hook/i.test(e.constructor.name))", by: 1590 },
  { id: 'd6-shafts-cast2', after: 1591, plus: 0, whole: true, until: "g.entities.some(e => /dredge|lure|hook/i.test(e.constructor.name))", by: 1593 },
  { id: 'd6-brinehulk', after: 1595, plus: 90, whole: true },
  { id: 'd6-brinehulk-fight', after: 1595, plus: 300 },
  { id: 'd6-stairhead', after: 1620, plus: 5, whole: true },
  { id: 'd6-nereth-intro', after: 1629, plus: 5, whole: true },
  { id: 'd6-nereth-a', after: 1629, plus: 600 },
  { id: 'd6-nereth-b', after: 1629, plus: 900 },
  { id: 'd6-nereth-c', after: 1629, plus: 1500 },
  { id: 'd6-nereth-d', after: 1629, plus: 2200 },
  { id: 'd6-essence', after: 1634, plus: 30 },
  { id: 'd6-end', after: 1636, plus: 0, until: "g.mode === 'theend'", by: 1637 },
];

const D1 = ['3,7','3,6','2,6','3,5','2,5','4,5','3,4','2,4','4,4','3,3','2,3','3,2','4,2','5,2','5,1','4,1','5,3','4,3','2,2','1,2','1,3','1,1','2,1','3,1'];
export const STATIC_SHOTS = [
  { id: 'title', title: true, frames: 400 },
  { id: 'menu-anchor', room: ['d1', 0, 3, 2], tide: 0, whole: false, player: true, keepDialogue: true,
    // Seasons' item page (S176): what is on B and A is up in the status bar,
    // the rest in the grid; the cursor on the Anchor, its name below.
    prep: { script: "Object.assign(g.progress.items, { sword: 1, shield: 1, conch: 1, anchor: 1, cleats: 1, lens: 1 }); g.progress.equipB = 'shield'; g.progress.equipA = 'sword'; g.menu.open(); H.step(60); g.menu.cursor = g.menu.items.findIndex(t => t && t.id === 'anchor'); H.step(30);" } },
];
// The overworld is OVERWORLD_W screens across since S157 (CLAUDE.md: never
// write the width down).
import { OVERWORLD_W } from '../../src/data/overworld.js';
for (let ry = 0; ry < 10; ry++) for (let rx = 0; rx < OVERWORLD_W; rx++) {
  for (const t of [1]) STATIC_SHOTS.push({ id: `ow-t${t}-${rx}-${ry}`, room: ['overworld', 0, rx, ry], tide: t });
}
for (const t of [0, 1, 2]) for (const k of D1) {
  const [rx, ry] = k.split(',').map(Number);
  STATIC_SHOTS.push({ id: `d1map-t${t}-${rx}${ry}`, room: ['d1', 0, rx, ry], tide: t });
}

// Every room of dungeons 2-6 at MID, empty of Link, for the stitched maps.
import { DUNGEON_ROOMS } from './rooms-list.mjs';
for (const [map, keys] of Object.entries(DUNGEON_ROOMS)) for (const k of keys) {
  const [f, rx, ry] = k.split(',').map(Number);
  STATIC_SHOTS.push({ id: `${map}map-${f}-${rx}-${ry}`, room: [map, f, rx, ry], tide: 1 });
}
for (const c of ['cave1', 'cave2', 'cave3', 'cave4', 'cave5', 'cave6', 'caveShipwright']) STATIC_SHOTS.push({ id: `${c}-room`, room: [c, 0, 0, 0], tide: 1 });
STATIC_SHOTS.push({ id: 'cave2-low', room: ['cave2', 0, 0, 0], tide: 0 });
// The optional dungeons' Pieces of Heart (S160, S161), for the heart list.
STATIC_SHOTS.push({ id: 'opt-vault-pan', room: ['vault', 0, 1, 0], tide: 1 });
STATIC_SHOTS.push({ id: 'opt-eyrie-roost', room: ['eyrie', 0, 1, 0], tide: 1 });
STATIC_SHOTS.push({ id: 'opt-palace-chapel', room: ['palace', 1, 0, 2], tide: 0 });
STATIC_SHOTS.push({ id: 'opt-palace-lair', room: ['palace', 0, 1, 0], tide: 1 });

// The Slackwater Cave's mouth, open only at LOW (S155 side content).
STATIC_SHOTS.push({ id: 'ow-t0-1-2', room: ['overworld', 0, 1, 2], tide: 0 });
