// The moments the guide photographs. See capture.mjs for what `after`,
// `until` and `plus` mean. Route shots must stay in route order.
const DLG = 'g.dialogue.active && g.dialogue.chars >= g.dialogue.pageLen';
const ANCHOR_FLYING = "g.entities.some(e => e.sprite === 'o_anchor' && e.state === 'flight')";
const ANCHOR_HELD = "g.entities.some(e => e.sprite === 'o_anchor' && e.state === 'held')";
const ITEM = 'g.itemShow && g.itemShow.t < 100';
const IN = (k) => `g.room && g.mapId + ' ' + g.room.key === ${JSON.stringify(k)}`;

export const ROUTE_SHOTS = [
  // --------------------------------------------------------- the start
  // S159: the opening since S158 — washed up on the Fishing Stones with
  // nothing, Teel, Wenna in Palisade Row, the sword in the Shipwright's
  // Hollow, Farore's shrine on Tern Point, then the Maku Tree's key.
  { id: 'intro-wake', after: 0, plus: 30, whole: true },
  { id: 'intro-teel', after: 0, until: DLG, plus: 2, by: 1 },
  { id: 'intro-wenna', after: 2, until: DLG, plus: 2, by: 3 },
  { id: 'intro-gull', after: 4, plus: 0, whole: true },
  { id: 'intro-hollow', after: 7, plus: 5, whole: true },
  { id: 'intro-sword', after: 11, until: ITEM, plus: 30, by: 12 },
  { id: 'intro-tern', after: 15, plus: 0, whole: true },
  { id: 'intro-farore', after: 17, until: DLG, plus: 2, by: 18 },
  { id: 'intro-conch', after: 17, until: ITEM, plus: 30, by: 18 },
  { id: 'village', after: 23, plus: 30, whole: true },
  { id: 'village-hud', after: 23, plus: 30 },
  { id: 'intro-maku', after: 25, until: DLG, plus: 2, by: 26 },
  { id: 'village-conch', after: 42, until: 'g.tide.busy', plus: 10, by: 43 },
  { id: 'ow-grotto', after: 53, plus: 0, whole: true },
  // --------------------------------------------------------------- D1
  { id: 'd1-enter', after: 55, until: IN('d1 0,3,7'), plus: 70, whole: true },
  { id: 'd1-mouth-conch', after: 58, until: 'g.tide.busy', plus: 8, by: 59, whole: true },
  { id: 'd1-mouth-low', after: 60, whole: true },
  { id: 'd1-drink', after: 61, plus: 20, whole: true },
  { id: 'd1-hall', after: 65, plus: 30, whole: true },
  { id: 'd1-hall-push1', after: 69, plus: 40, whole: true },
  { id: 'd1-hall-push2', after: 71, plus: 60, whole: true },
  { id: 'd1-hall-fairy', after: 73, plus: 10, whole: true },
  { id: 'd1-mapalcove', after: 75, plus: 20, whole: true },
  { id: 'd1-chart', after: 82, plus: 10, whole: true },
  { id: 'd1-chart-open', after: 87, until: 'g.dialogue.active', plus: 20 },
  { id: 'd1-gallery', after: 90, plus: 10, whole: true },
  { id: 'd1-crabpit', after: 94, plus: 30, whole: true },
  { id: 'd1-crabpit-key', after: 96, until: DLG, plus: 2, whole: true },
  { id: 'd1-switch', after: 99, plus: 10, whole: true },
  { id: 'd1-switch-done', after: 105, until: DLG, plus: 2, whole: true },
  { id: 'd1-gallery-door', after: 112, until: DLG, plus: 1, whole: true },
  { id: 'd1-stair', after: 115, plus: 30, whole: true },
  
  { id: 'd1-sluicegate', after: 123, plus: 20, whole: true },
  { id: 'd1-anchor-get', after: 126, until: 'g.dialogue.active', plus: 20 },
  { id: 'd1-anchor-menu', after: 129, until: "g.mode === 'menu'", plus: 60 },
  { id: 'd1-pipe', after: 131, plus: 10, whole: true },
  { id: 'd1-pipe-throw', after: 131, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-pipe-held', after: 132, plus: 0, whole: true },
  { id: 'd1-pipe-mid', after: 133, plus: 30, whole: true },
  { id: 'd1-chamber', after: 135, plus: 10, whole: true },
  { id: 'd1-chamber-low', after: 136, plus: 5, whole: true },
  { id: 'd1-race', after: 139, plus: 10, whole: true },
  { id: 'd1-race-throw', after: 140, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-race-mid', after: 142, plus: 30, whole: true },
  { id: 'd1-keyvault', after: 144, plus: 10, whole: true },
  { id: 'd1-keyvault-key', after: 150, plus: 30 },
  { id: 'd1-den', after: 163, plus: 10, whole: true },
  { id: 'd1-den-fight1', after: 164, plus: 280, whole: true },
  { id: 'd1-den-fight2', after: 164, plus: 120 },
  { id: 'd1-den-fight3', after: 164, plus: 180 },
  { id: 'd1-den-piece', after: 167, plus: 10, whole: true },
  { id: 'd1-den-door', after: 171, plus: 2 },
  { id: 'd1-gauges', after: 174, plus: 10, whole: true },
  { id: 'd1-gauges-low', after: 177, plus: 5, whole: true },
  { id: 'd1-gauges-throw', after: 177, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-gauges-open', after: 179, until: DLG, plus: 2, whole: true },
  { id: 'd1-gauges-piece', after: 181, plus: 12 },
  { id: 'd1-gauges-stair', after: 183, plus: 60, whole: true },
  { id: 'd1-stair2', after: 184, plus: 10, whole: true },
  { id: 'd1-sluice', after: 196, plus: 10, whole: true },
  { id: 'd1-sluice-throw1', after: 196, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-sluice-low', after: 198, plus: 5, whole: true },
  { id: 'd1-sluice-throw2', after: 199, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-sluice-mid', after: 201, plus: 30, whole: true },
  { id: 'd1-turn', after: 203, plus: 10, whole: true },
  { id: 'd1-drip', after: 205, plus: 10, whole: true },
  { id: 'd1-drip-throw', after: 210, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-drip-open', after: 212, plus: 0, whole: true },
  { id: 'd1-bkvault', after: 215, plus: 10, whole: true },
  { id: 'd1-bosskey', after: 219, plus: 30 },
  { id: 'd1-bossdoor', after: 232, plus: 2, whole: true },
  { id: 'd1-boss-intro', after: 235, plus: 40, whole: true },
  { id: 'd1-boss-a', after: 236, plus: 40 },
  { id: 'd1-boss-b', after: 236, plus: 70 },
  { id: 'd1-boss-c', after: 236, plus: 70 },
  { id: 'd1-boss-d', after: 236, plus: 70 },
  { id: 'd1-boss-e', after: 236, plus: 70 },
  { id: 'd1-boss-f', after: 236, plus: 70 },
  { id: 'd1-boss-g', after: 236, plus: 70 },
  { id: 'd1-boss-h', after: 236, plus: 70 },
  { id: 'd1-boss-won', after: 238, plus: 0, whole: true },
  { id: 'd1-essence', after: 239, until: DLG, plus: 2, by: 242 },
  { id: 'end-d1', after: 245 },
  { id: 'ow2-shop', after: 251, plus: 2 },
  { id: 'ow2-sandpiper', after: 270, plus: 0, whole: true },
  { id: 'd2-mouth', after: 281, plus: 20, whole: true },
  { id: 'd2-landing', after: 283, plus: 5, whole: true },
  { id: 'd2-landing-fairy', after: 284, plus: 20, whole: true },
  { id: 'ow2-shellflats', after: 297, plus: 5, whole: true },
  { id: 'd2-rising', after: 310, plus: 5, whole: true },
  { id: 'd2-rising-done', after: 315, plus: 20, whole: true },
  { id: 'd2-coil', after: 325, plus: 0, whole: true },
  { id: 'd2-sealed', after: 329, plus: 5, whole: true },
  { id: 'd2-lens-get', after: 332, plus: 30 },
  { id: 'd2-glass', after: 336, plus: 60, whole: true },
  { id: 'd2-glass-lens', after: 336, plus: 0, until: 'g.player && g.player.lensT > 0', by: 337 },
  { id: 'd2-glass-piece', after: 338, plus: 5, whole: true },
  { id: 'd2-fork1', after: 341, plus: 5, whole: true },
  { id: 'd2-fork1-valve', after: 345, plus: 30, whole: true },
  { id: 'd2-reefguard', after: 348, plus: 60, whole: true },
  { id: 'd2-reefguard-fight', after: 348, plus: 200 },
  { id: 'd2-reefguard-key', after: 357, plus: 5, whole: true },
  { id: 'd2-bombvault', after: 359, plus: 5, whole: true },
  { id: 'd2-bombs-get', after: 362, plus: 30 },
  { id: 'd2-whelk', after: 365, plus: 5, whole: true },
  { id: 'd2-ascent', after: 370, plus: 5, whole: true },
  { id: 'd2-soundfork', after: 376, plus: 5, whole: true },
  { id: 'd2-soundfork-valve', after: 381, plus: 30, whole: true },
  { id: 'd2-bosskey', after: 383, plus: 5, whole: true },
  { id: 'd2-bosskey-get', after: 386, plus: 30 },
  { id: 'd2-bossdoor', after: 396, plus: 5, whole: true },
  { id: 'd2-boss-intro', after: 400, plus: 60, whole: true },
  { id: 'd2-boss-a', after: 400, plus: 300 },
  { id: 'd2-boss-b', after: 400, plus: 300 },
  { id: 'd2-boss-c', after: 400, plus: 400 },
  { id: 'd2-boss-d', after: 400, plus: 500 },
  { id: 'd2-essence', after: 403, plus: 0, whole: true },
  { id: 'ow3-causeway', after: 439, plus: 5, whole: true },
  { id: 'ow3-bomb', after: 443, plus: 30, whole: true },
  { id: 'ow3-open', after: 445, plus: 0, whole: true },
  { id: 'd3-mouth', after: 450, plus: 10, whole: true },
  { id: 'd3-nave', after: 451, until: IN('d3 1,3,6'), plus: 2, by: 452, whole: true },
  { id: 'd3-mapcell', after: 460, plus: 5, whole: true },
  { id: 'd3-hub', after: 467, plus: 5, whole: true },
  { id: 'd3-pens', after: 470, plus: 5, whole: true },
  { id: 'd3-landing', after: 478, plus: 5, whole: true },
  { id: 'd3-sluice', after: 489, plus: 0, whole: true },
  { id: 'd3-sluice-mid', after: 490, plus: 5, whole: true },
  { id: 'd3-drainweir', after: 493, plus: 5, whole: true },
  { id: 'd3-weir', after: 510, plus: 5, whole: true },
  { id: 'd3-silt', after: 515, plus: 5, whole: true },
  { id: 'd3-rootcellar', after: 516, plus: 5, whole: true },
  { id: 'd3-reed', after: 528, plus: 5, whole: true },
  { id: 'd3-cistern', after: 537, plus: 5, whole: true },
  { id: 'd3-cleats-get', after: 540, plus: 30 },
  { id: 'd3-cistern-sink', after: 545, plus: 20, whole: true },
  { id: 'd3-undertow', after: 546, plus: 30, whole: true },
  { id: 'd3-vestry', after: 549, plus: 5, whole: true },
  { id: 'd3-vestry-done', after: 554, plus: 5, whole: true },
  { id: 'd3-drain-gallery', after: 562, plus: 5, whole: true },
  { id: 'd3-bosskey-get', after: 566, plus: 30 },
  { id: 'd3-bogmaw', after: 569, plus: 5, whole: true },
  { id: 'd3-bogmaw-fight', after: 571, plus: 200 },
  { id: 'd3-roof', after: 577, plus: 5, whole: true },
  { id: 'd3-drain', after: 585, plus: 5, whole: true },
  { id: 'd3-eelhall', after: 596, plus: 5, whole: true },
  { id: 'd3-eelvault', after: 611, plus: 5, whole: true },
  { id: 'd3-soundpool', after: 632, plus: 5, whole: true },
  { id: 'd3-soundpool-sink', after: 636, plus: 60, whole: true },
  { id: 'd3-weights', after: 642, plus: 5, whole: true },
  { id: 'd3-weights-push', after: 647, plus: 5, whole: true },
  { id: 'd3-weights-plate', after: 652, plus: 20, whole: true },
  { id: 'd3-kelp', after: 669, plus: 5, whole: true },
  { id: 'd3-kelp-sink', after: 675, plus: 40, whole: true },
  { id: 'd3-lockgallery', after: 678, plus: 5, whole: true },
  { id: 'd3-bossdoor', after: 686, plus: 5, whole: true },
  { id: 'd3-boss-intro', after: 688, plus: 60, whole: true },
  { id: 'd3-boss-a', after: 688, plus: 400 },
  { id: 'd3-boss-b', after: 688, plus: 600 },
  { id: 'd3-boss-c', after: 688, plus: 900 },
  { id: 'ow4-deepcut', after: 725, plus: 5, whole: true },
  { id: 'ow4-bomb', after: 730, plus: 30, whole: true },
  { id: 'ow4-cistmouth', after: 739, plus: 5, whole: true },
  { id: 'd4-head', after: 742, plus: 20, whole: true },
  { id: 'd4-basin', after: 746, plus: 5, whole: true },
  { id: 'd4-weir', after: 750, plus: 5, whole: true },
  { id: 'd4-floor', after: 757, plus: 5, whole: true },
  { id: 'd4-floor-push', after: 760, plus: 5, whole: true },
  { id: 'd4-floor-plate', after: 763, plus: 5, whole: true },
  { id: 'd4-winch', after: 768, plus: 5, whole: true },
  { id: 'd4-bellowsvault', after: 774, plus: 5, whole: true },
  { id: 'd4-bellows-get', after: 777, plus: 30 },
  { id: 'd4-loft', after: 781, plus: 5, whole: true },
  { id: 'd4-loft-blow', after: 785, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 787 },
  { id: 'd4-ebb', after: 791, plus: 5, whole: true },
  { id: 'd4-ebb-high', after: 794, plus: 5, whole: true },
  { id: 'd4-ebb-blow', after: 796, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 798 },
  { id: 'd4-spillvault', after: 801, plus: 5, whole: true },
  { id: 'd4-dsill', after: 812, plus: 5, whole: true },
  { id: 'd4-dsill-blow', after: 815, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 818 },
  { id: 'd4-gauge', after: 819, plus: 5, whole: true },
  { id: 'd4-gauge-blow', after: 822, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 825 },
  { id: 'd4-overlook', after: 829, plus: 5, whole: true },
  { id: 'd4-stair', after: 834, plus: 5, whole: true },
  { id: 'd4-race', after: 841, plus: 5, whole: true },
  { id: 'd4-race-blow1', after: 843, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 846 },
  { id: 'd4-race-blow2', after: 847, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 849 },
  { id: 'd4-ironknight', after: 851, plus: 60, whole: true },
  { id: 'd4-ironknight-fight', after: 852, plus: 300 },
  { id: 'd4-cliffwalk', after: 857, plus: 5, whole: true },
  { id: 'd4-crossed', after: 865, plus: 5, whole: true },
  { id: 'd4-crossed-blow1', after: 868, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 871 },
  { id: 'd4-crossed-blow2', after: 873, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 875 },
  { id: 'd4-crossed-key', after: 877, plus: 5, whole: true },
  { id: 'd4-eastlook', after: 880, plus: 5, whole: true },
  { id: 'd4-gate', after: 887, plus: 5, whole: true },
  { id: 'd4-boss-intro', after: 895, plus: 90, whole: true },
  { id: 'd4-boss-a', after: 896, plus: 600 },
  { id: 'd4-boss-b', after: 896, plus: 800 },
  { id: 'd4-boss-c', after: 896, plus: 1200 },
  { id: 'ow5-noble', after: 928, plus: 40 },
  { id: 'ow5-shrinemouth', after: 938, plus: 5, whole: true },
  { id: 'd5-landing', after: 944, plus: 5, whole: true },
  { id: 'd5-silt', after: 947, plus: 5, whole: true },
  { id: 'd5-bracken', after: 954, plus: 5, whole: true },
  { id: 'd5-chartnave', after: 959, plus: 5, whole: true },
  { id: 'd5-cloister', after: 968, plus: 5, whole: true },
  { id: 'd5-cloister-high', after: 970, plus: 5, whole: true },
  { id: 'd5-thicket', after: 975, plus: 5, whole: true },
  { id: 'd5-bower', after: 984, plus: 5, whole: true },
  { id: 'd5-bower-blow', after: 986, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 989 },
  { id: 'd5-grove', after: 994, plus: 5, whole: true },
  { id: 'd5-rootbound', after: 1001, plus: 5, whole: true },
  { id: 'd5-sbracken', after: 1003, plus: 5, whole: true },
  { id: 'd5-warden', after: 1019, plus: 5, whole: true },
  { id: 'd5-seedvault', after: 1027, plus: 5, whole: true },
  { id: 'd5-seed-get', after: 1031, plus: 30 },
  { id: 'd5-stake1', after: 1035, plus: 5, whole: true },
  { id: 'd5-stake1-high', after: 1037, plus: 5, whole: true },
  { id: 'd5-stake1-throw', after: 1037, plus: 0, whole: true, until: "g.entities.some(e => e.constructor && /seed/i.test(e.constructor.name))", by: 1039 },
  { id: 'd5-stake1-low', after: 1039, plus: 60, whole: true },
  { id: 'd5-stake1-cut', after: 1043, plus: 5, whole: true },
  { id: 'd5-bolewalk', after: 1047, plus: 5, whole: true },
  { id: 'd5-bolewalk-low', after: 1053, plus: 60, whole: true },
  { id: 'd5-snave', after: 1061, plus: 5, whole: true },
  { id: 'd5-snave-low', after: 1066, plus: 60, whole: true },
  { id: 'd5-knotted', after: 1083, plus: 5, whole: true },
  { id: 'd5-knotted-low', after: 1090, plus: 60, whole: true },
  { id: 'd5-knotted-2', after: 1091, plus: 60, whole: true },
  { id: 'd5-rootford', after: 1099, plus: 5, whole: true },
  { id: 'd5-rootford-low', after: 1105, plus: 40, whole: true },
  { id: 'd5-rootford-pushed', after: 1112, plus: 5, whole: true },
  { id: 'd5-crossing', after: 1138, plus: 5, whole: true },
  { id: 'd5-longford', after: 1142, plus: 5, whole: true },
  { id: 'd5-longford-low', after: 1148, plus: 60, whole: true },
  { id: 'd5-thornvine', after: 1159, plus: 60, whole: true },
  { id: 'd5-thornvine-fight', after: 1159, plus: 100 },
  { id: 'd5-shrineford', after: 1166, plus: 5, whole: true },
  { id: 'd5-shrineford-2', after: 1171, plus: 60, whole: true },
  { id: 'd5-arch', after: 1186, plus: 5, whole: true },
  { id: 'd5-boss-intro', after: 1193, plus: 90, whole: true },
  { id: 'd5-boss-a', after: 1194, plus: 500 },
  { id: 'd5-boss-b', after: 1194, plus: 800 },
  { id: 'd5-boss-c', after: 1194, plus: 1000 },
  { id: 'ow6-maku', after: 1359, plus: 5, whole: true },
  { id: 'ow6-rod', after: 1360, plus: 5 },
  { id: 'ow6-gate', after: 1390, plus: 5, whole: true },
  { id: 'd6-door', after: 1393, plus: 10, whole: true },
  { id: 'd6-bone', after: 1399, plus: 5, whole: true },
  { id: 'd6-drain', after: 1404, plus: 5, whole: true },
  { id: 'd6-drain-done', after: 1408, plus: 5, whole: true },
  { id: 'd6-kiln', after: 1414, plus: 5, whole: true },
  { id: 'd6-kiln-lit', after: 1432, plus: 60, whole: true },
  { id: 'd6-crypt', after: 1438, plus: 5, whole: true },
  { id: 'd6-crypt-blow', after: 1440, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 1442 },
  { id: 'd6-heights', after: 1444, plus: 5, whole: true },
  { id: 'd6-lock', after: 1450, plus: 5, whole: true },
  { id: 'd6-dredgevault', after: 1465, plus: 5, whole: true },
  { id: 'd6-dredge-get', after: 1468, plus: 30 },
  { id: 'd6-slack', after: 1474, plus: 5, whole: true },
  { id: 'd6-slack-cast', after: 1475, plus: 0, whole: true, until: "g.entities.some(e => /dredge|lure|hook/i.test(e.constructor.name))", by: 1477 },
  { id: 'd6-draw', after: 1478, plus: 5, whole: true },
  { id: 'd6-draw-cast', after: 1483, plus: 0, whole: true, until: "g.entities.some(e => /dredge|lure|hook/i.test(e.constructor.name))", by: 1485 },
  { id: 'd6-tally', after: 1490, plus: 5, whole: true },
  { id: 'd6-hauling', after: 1505, plus: 5, whole: true },
  { id: 'd6-upper', after: 1533, plus: 5, whole: true },
  { id: 'd6-tideshade', after: 1537, plus: 60, whole: true },
  { id: 'd6-tideshade-fight', after: 1537, plus: 300 },
  { id: 'd6-mermaid', after: 1542, plus: 5, whole: true },
  { id: 'd6-arches', after: 1549, plus: 5, whole: true },
  { id: 'd6-arches-lens', after: 1552, plus: 0, until: 'g.player && g.player.lensHeld', by: 1554 },
  { id: 'd6-shade', after: 1573, plus: 5, whole: true },
  { id: 'd6-colonnade', after: 1581, plus: 5, whole: true },
  { id: 'd6-colonnade-rod', after: 1583, plus: 5, whole: true },
  { id: 'd6-stand', after: 1595, plus: 5, whole: true },
  { id: 'd6-crossing', after: 1600, plus: 5, whole: true },
  { id: 'd6-bar', after: 1601, plus: 5, whole: true },
  { id: 'd6-sill', after: 1626, plus: 5, whole: true },
  { id: 'd6-gate', after: 1646, plus: 5, whole: true },
  { id: 'd6-shafts', after: 1652, plus: 5, whole: true },
  { id: 'd6-shafts-cast1', after: 1653, plus: 0, whole: true, until: "g.entities.some(e => /dredge|lure|hook/i.test(e.constructor.name))", by: 1655 },
  { id: 'd6-shafts-cast2', after: 1656, plus: 0, whole: true, until: "g.entities.some(e => /dredge|lure|hook/i.test(e.constructor.name))", by: 1658 },
  { id: 'd6-brinehulk', after: 1660, plus: 90, whole: true },
  { id: 'd6-brinehulk-fight', after: 1660, plus: 300 },
  { id: 'd6-stairhead', after: 1685, plus: 5, whole: true },
  { id: 'd6-nereth-intro', after: 1694, plus: 5, whole: true },
  { id: 'd6-nereth-a', after: 1694, plus: 600 },
  { id: 'd6-nereth-b', after: 1694, plus: 900 },
  { id: 'd6-nereth-c', after: 1694, plus: 1500 },
  { id: 'd6-nereth-d', after: 1694, plus: 2200 },
  { id: 'd6-essence', after: 1699, plus: 30 },
  { id: 'd6-end', after: 1701, plus: 0, until: "g.mode === 'theend'", by: 1702 },
];

const D1 = ['3,7','3,6','2,6','3,5','2,5','4,5','3,4','2,4','4,4','3,3','2,3','3,2','4,2','5,2','5,1','4,1','5,3','4,3','2,2','1,2','1,3','1,1','2,1','3,1'];
export const STATIC_SHOTS = [
  { id: 'title', title: true, frames: 400 },
  { id: 'menu-anchor', room: ['d1', 0, 3, 2], tide: 0, whole: false, player: true, keepDialogue: true,
    // Seasons' item page (S176): what is on B and A is up in the status bar,
    // the rest in the grid; the cursor on the Anchor, its name below.
    prep: { script: "Object.assign(g.progress.items, { sword: 1, shield: 1, conch: 1, anchor: 1, cleats: 1, lens: 1 }); g.progress.equipB = 'shield'; g.progress.equipA = 'sword'; g.menu.open(); H.step(60); g.menu.cursor = g.menu.items.findIndex(t => t && t.id === 'anchor'); H.step(30);" } },
];
// The overworld is OVERWORLD_W screens across since S157 (CLAUDE.md: never
// write the width down).
import { OVERWORLD_W } from '../../src/data/overworld.js';
for (let ry = 0; ry < 10; ry++) for (let rx = 0; rx < OVERWORLD_W; rx++) {
  for (const t of [1]) STATIC_SHOTS.push({ id: `ow-t${t}-${rx}-${ry}`, room: ['overworld', 0, rx, ry], tide: t });
}
for (const t of [0, 1, 2]) for (const k of D1) {
  const [rx, ry] = k.split(',').map(Number);
  STATIC_SHOTS.push({ id: `d1map-t${t}-${rx}${ry}`, room: ['d1', 0, rx, ry], tide: t });
}

// Every room of dungeons 2-6 at MID, empty of Link, for the stitched maps.
import { DUNGEON_ROOMS } from './rooms-list.mjs';
for (const [map, keys] of Object.entries(DUNGEON_ROOMS)) for (const k of keys) {
  const [f, rx, ry] = k.split(',').map(Number);
  STATIC_SHOTS.push({ id: `${map}map-${f}-${rx}-${ry}`, room: [map, f, rx, ry], tide: 1 });
}
for (const c of ['cave1', 'cave2', 'cave3', 'cave4', 'cave5', 'cave6', 'caveShipwright']) STATIC_SHOTS.push({ id: `${c}-room`, room: [c, 0, 0, 0], tide: 1 });
STATIC_SHOTS.push({ id: 'cave2-low', room: ['cave2', 0, 0, 0], tide: 0 });
// The optional dungeons' Pieces of Heart (S160, S161), for the heart list.
STATIC_SHOTS.push({ id: 'opt-vault-pan', room: ['vault', 0, 1, 0], tide: 1 });
STATIC_SHOTS.push({ id: 'opt-eyrie-roost', room: ['eyrie', 0, 1, 0], tide: 1 });
STATIC_SHOTS.push({ id: 'opt-palace-chapel', room: ['palace', 1, 0, 2], tide: 0 });
STATIC_SHOTS.push({ id: 'opt-palace-lair', room: ['palace', 0, 1, 0], tide: 1 });

// The Slackwater Cave's mouth, open only at LOW (S155 side content).
STATIC_SHOTS.push({ id: 'ow-t0-1-2', room: ['overworld', 0, 1, 2], tide: 0 });
