// The moments the guide photographs. See capture.mjs for what `after`,
// `until` and `plus` mean. Route shots must stay in route order.
const DLG = 'g.dialogue.active && g.dialogue.chars >= g.dialogue.pageLen';
const ANCHOR_FLYING = "g.entities.some(e => e.sprite === 'o_anchor' && e.state === 'flight')";
const ANCHOR_HELD = "g.entities.some(e => e.sprite === 'o_anchor' && e.state === 'held')";
const ITEM = 'g.itemShow && g.itemShow.t < 100';
const IN = (k) => `g.room && g.mapId + ' ' + g.room.key === ${JSON.stringify(k)}`;

export const ROUTE_SHOTS = [
  // --------------------------------------------------------- the start
  // S159: the opening since S158 — washed up on the Fishing Stones with
  // nothing, Teel, Wenna in Palisade Row, the sword in the Shipwright's
  // Hollow, Farore's shrine on Tern Point, then the Maku Tree's key.
  { id: 'intro-wake', after: 0, plus: 30, whole: true },
  { id: 'intro-teel', after: 0, until: DLG, plus: 2, by: 1 },
  { id: 'intro-wenna', after: 2, until: DLG, plus: 2, by: 3 },
  { id: 'intro-gull', after: 4, plus: 0, whole: true },
  { id: 'intro-hollow', after: 7, plus: 5, whole: true },
  { id: 'intro-sword', after: 11, until: ITEM, plus: 30, by: 12 },
  { id: 'intro-tern', after: 15, plus: 0, whole: true },
  { id: 'intro-farore', after: 17, until: DLG, plus: 2, by: 18 },
  { id: 'intro-conch', after: 17, until: ITEM, plus: 30, by: 18 },
  { id: 'village', after: 23, plus: 30, whole: true },
  { id: 'village-hud', after: 23, plus: 30 },
  { id: 'intro-maku', after: 25, until: DLG, plus: 2, by: 26 },
  { id: 'village-conch', after: 42, until: 'g.tide.busy', plus: 10, by: 43 },
  { id: 'ow-grotto', after: 53, plus: 0, whole: true },
  // --------------------------------------------------------------- D1
  { id: 'd1-enter', after: 55, until: IN('d1 0,3,7'), plus: 70, whole: true },
  { id: 'd1-mouth-conch', after: 58, until: 'g.tide.busy', plus: 8, by: 59, whole: true },
  { id: 'd1-mouth-low', after: 60, whole: true },
  { id: 'd1-drink', after: 61, plus: 20, whole: true },
  { id: 'd1-hall', after: 65, plus: 30, whole: true },
  { id: 'd1-hall-push1', after: 69, plus: 40, whole: true },
  { id: 'd1-hall-push2', after: 71, plus: 60, whole: true },
  { id: 'd1-hall-fairy', after: 73, plus: 10, whole: true },
  { id: 'd1-mapalcove', after: 75, plus: 20, whole: true },
  { id: 'd1-chart', after: 78, plus: 10, whole: true },
  { id: 'd1-chart-open', after: 83, until: 'g.dialogue.active', plus: 20 },
  { id: 'd1-gallery', after: 86, plus: 10, whole: true },
  { id: 'd1-crabpit', after: 90, plus: 30, whole: true },
  { id: 'd1-crabpit-key', after: 92, until: DLG, plus: 2, whole: true },
  { id: 'd1-switch', after: 95, plus: 10, whole: true },
  { id: 'd1-switch-done', after: 101, until: DLG, plus: 2, whole: true },
  { id: 'd1-gallery-door', after: 108, until: DLG, plus: 1, whole: true },
  { id: 'd1-stair', after: 111, plus: 30, whole: true },
  
  { id: 'd1-sluicegate', after: 119, plus: 20, whole: true },
  { id: 'd1-anchor-get', after: 122, until: 'g.dialogue.active', plus: 20 },
  { id: 'd1-anchor-menu', after: 125, until: "g.mode === 'menu'", plus: 60 },
  { id: 'd1-pipe', after: 127, plus: 10, whole: true },
  { id: 'd1-pipe-throw', after: 127, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-pipe-held', after: 128, plus: 0, whole: true },
  { id: 'd1-pipe-mid', after: 129, plus: 30, whole: true },
  { id: 'd1-chamber', after: 131, plus: 10, whole: true },
  { id: 'd1-chamber-low', after: 132, plus: 5, whole: true },
  { id: 'd1-race', after: 135, plus: 10, whole: true },
  { id: 'd1-race-throw', after: 136, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-race-mid', after: 138, plus: 30, whole: true },
  { id: 'd1-keyvault', after: 140, plus: 10, whole: true },
  { id: 'd1-keyvault-key', after: 146, plus: 30 },
  { id: 'd1-den', after: 159, plus: 10, whole: true },
  { id: 'd1-den-fight1', after: 160, plus: 280, whole: true },
  { id: 'd1-den-fight2', after: 160, plus: 120 },
  { id: 'd1-den-fight3', after: 160, plus: 180 },
  { id: 'd1-den-piece', after: 163, plus: 10, whole: true },
  { id: 'd1-den-door', after: 167, plus: 2 },
  { id: 'd1-gauges', after: 170, plus: 10, whole: true },
  { id: 'd1-gauges-low', after: 173, plus: 5, whole: true },
  { id: 'd1-gauges-throw', after: 173, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-gauges-open', after: 175, until: DLG, plus: 2, whole: true },
  { id: 'd1-gauges-piece', after: 177, plus: 12 },
  { id: 'd1-gauges-stair', after: 179, plus: 60, whole: true },
  { id: 'd1-stair2', after: 180, plus: 10, whole: true },
  { id: 'd1-sluice', after: 192, plus: 10, whole: true },
  { id: 'd1-sluice-throw1', after: 192, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-sluice-low', after: 194, plus: 5, whole: true },
  { id: 'd1-sluice-throw2', after: 195, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-sluice-mid', after: 197, plus: 30, whole: true },
  { id: 'd1-turn', after: 199, plus: 10, whole: true },
  { id: 'd1-drip', after: 201, plus: 10, whole: true },
  { id: 'd1-drip-throw', after: 206, until: ANCHOR_FLYING, plus: 6, whole: true },
  { id: 'd1-drip-open', after: 208, plus: 0, whole: true },
  { id: 'd1-bkvault', after: 211, plus: 10, whole: true },
  { id: 'd1-bosskey', after: 215, plus: 30 },
  { id: 'd1-bossdoor', after: 228, plus: 2, whole: true },
  { id: 'd1-boss-intro', after: 231, plus: 40, whole: true },
  { id: 'd1-boss-a', after: 232, plus: 40 },
  { id: 'd1-boss-b', after: 232, plus: 70 },
  { id: 'd1-boss-c', after: 232, plus: 70 },
  { id: 'd1-boss-d', after: 232, plus: 70 },
  { id: 'd1-boss-e', after: 232, plus: 70 },
  { id: 'd1-boss-f', after: 232, plus: 70 },
  { id: 'd1-boss-g', after: 232, plus: 70 },
  { id: 'd1-boss-h', after: 232, plus: 70 },
  { id: 'd1-boss-won', after: 234, plus: 0, whole: true },
  { id: 'd1-essence', after: 235, until: DLG, plus: 2, by: 238 },
  { id: 'end-d1', after: 241 },
  { id: 'ow2-shop', after: 247, plus: 2 },
  { id: 'ow2-sandpiper', after: 266, plus: 0, whole: true },
  { id: 'd2-mouth', after: 277, plus: 20, whole: true },
  { id: 'd2-landing', after: 279, plus: 5, whole: true },
  { id: 'd2-landing-fairy', after: 280, plus: 20, whole: true },
  { id: 'ow2-shellflats', after: 293, plus: 5, whole: true },
  { id: 'd2-rising', after: 306, plus: 5, whole: true },
  { id: 'd2-rising-done', after: 311, plus: 20, whole: true },
  { id: 'd2-coil', after: 321, plus: 0, whole: true },
  { id: 'd2-sealed', after: 325, plus: 5, whole: true },
  { id: 'd2-lens-get', after: 328, plus: 30 },
  { id: 'd2-glass', after: 332, plus: 60, whole: true },
  { id: 'd2-glass-lens', after: 332, plus: 0, until: 'g.player && g.player.lensT > 0', by: 333 },
  { id: 'd2-glass-piece', after: 334, plus: 5, whole: true },
  { id: 'd2-fork1', after: 337, plus: 5, whole: true },
  { id: 'd2-fork1-valve', after: 341, plus: 30, whole: true },
  { id: 'd2-reefguard', after: 344, plus: 60, whole: true },
  { id: 'd2-reefguard-fight', after: 344, plus: 200 },
  { id: 'd2-reefguard-key', after: 353, plus: 5, whole: true },
  { id: 'd2-bombvault', after: 355, plus: 5, whole: true },
  { id: 'd2-bombs-get', after: 358, plus: 30 },
  { id: 'd2-whelk', after: 361, plus: 5, whole: true },
  { id: 'd2-ascent', after: 366, plus: 5, whole: true },
  { id: 'd2-soundfork', after: 372, plus: 5, whole: true },
  { id: 'd2-soundfork-valve', after: 377, plus: 30, whole: true },
  { id: 'd2-bosskey', after: 379, plus: 5, whole: true },
  { id: 'd2-bosskey-get', after: 382, plus: 30 },
  { id: 'd2-bossdoor', after: 392, plus: 5, whole: true },
  { id: 'd2-boss-intro', after: 396, plus: 60, whole: true },
  { id: 'd2-boss-a', after: 396, plus: 300 },
  { id: 'd2-boss-b', after: 396, plus: 300 },
  { id: 'd2-boss-c', after: 396, plus: 400 },
  { id: 'd2-boss-d', after: 396, plus: 500 },
  { id: 'd2-essence', after: 399, plus: 0, whole: true },
  { id: 'ow3-causeway', after: 435, plus: 5, whole: true },
  { id: 'ow3-bomb', after: 439, plus: 30, whole: true },
  { id: 'ow3-open', after: 441, plus: 0, whole: true },
  { id: 'd3-mouth', after: 446, plus: 10, whole: true },
  { id: 'd3-nave', after: 448, plus: 5, whole: true },
  { id: 'd3-mapcell', after: 455, plus: 5, whole: true },
  { id: 'd3-sluice', after: 457, plus: 5, whole: true },
  { id: 'd3-sluice-done', after: 461, plus: 5, whole: true },
  { id: 'd3-weir', after: 466, plus: 5, whole: true },
  { id: 'd3-silt', after: 470, plus: 5, whole: true },
  { id: 'd3-reed', after: 476, plus: 5, whole: true },
  { id: 'd3-cistern', after: 485, plus: 5, whole: true },
  { id: 'd3-cleats-get', after: 488, plus: 30 },
  { id: 'd3-cistern-sink', after: 493, plus: 20, whole: true },
  { id: 'd3-undertow', after: 494, plus: 30, whole: true },
  { id: 'd3-vestry', after: 497, plus: 5, whole: true },
  { id: 'd3-vestry-done', after: 502, plus: 5, whole: true },
  { id: 'd3-drain-gallery', after: 510, plus: 5, whole: true },
  { id: 'd3-bosskey-get', after: 514, plus: 30 },
  { id: 'd3-bogmaw', after: 517, plus: 5, whole: true },
  { id: 'd3-bogmaw-fight', after: 519, plus: 200 },
  { id: 'd3-roof', after: 525, plus: 5, whole: true },
  { id: 'd3-drain', after: 533, plus: 5, whole: true },
  { id: 'd3-eelhall', after: 544, plus: 5, whole: true },
  { id: 'd3-eelvault', after: 559, plus: 5, whole: true },
  { id: 'd3-soundpool', after: 580, plus: 5, whole: true },
  { id: 'd3-soundpool-sink', after: 584, plus: 60, whole: true },
  { id: 'd3-weights', after: 590, plus: 5, whole: true },
  { id: 'd3-weights-push', after: 595, plus: 5, whole: true },
  { id: 'd3-weights-plate', after: 600, plus: 20, whole: true },
  { id: 'd3-kelp', after: 617, plus: 5, whole: true },
  { id: 'd3-kelp-sink', after: 623, plus: 40, whole: true },
  { id: 'd3-lockgallery', after: 626, plus: 5, whole: true },
  { id: 'd3-bossdoor', after: 634, plus: 5, whole: true },
  { id: 'd3-boss-intro', after: 636, plus: 60, whole: true },
  { id: 'd3-boss-a', after: 636, plus: 400 },
  { id: 'd3-boss-b', after: 636, plus: 600 },
  { id: 'd3-boss-c', after: 636, plus: 900 },
  { id: 'ow4-deepcut', after: 673, plus: 5, whole: true },
  { id: 'ow4-bomb', after: 678, plus: 30, whole: true },
  { id: 'ow4-cistmouth', after: 687, plus: 5, whole: true },
  { id: 'd4-head', after: 690, plus: 20, whole: true },
  { id: 'd4-basin', after: 694, plus: 5, whole: true },
  { id: 'd4-weir', after: 698, plus: 5, whole: true },
  { id: 'd4-floor', after: 705, plus: 5, whole: true },
  { id: 'd4-floor-push', after: 708, plus: 5, whole: true },
  { id: 'd4-floor-plate', after: 711, plus: 5, whole: true },
  { id: 'd4-winch', after: 716, plus: 5, whole: true },
  { id: 'd4-bellowsvault', after: 722, plus: 5, whole: true },
  { id: 'd4-bellows-get', after: 725, plus: 30 },
  { id: 'd4-loft', after: 729, plus: 5, whole: true },
  { id: 'd4-loft-blow', after: 733, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 735 },
  { id: 'd4-ebb', after: 739, plus: 5, whole: true },
  { id: 'd4-ebb-high', after: 742, plus: 5, whole: true },
  { id: 'd4-ebb-blow', after: 744, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 746 },
  { id: 'd4-spillvault', after: 749, plus: 5, whole: true },
  { id: 'd4-dsill', after: 760, plus: 5, whole: true },
  { id: 'd4-dsill-blow', after: 763, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 766 },
  { id: 'd4-gauge', after: 767, plus: 5, whole: true },
  { id: 'd4-gauge-blow', after: 770, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 773 },
  { id: 'd4-overlook', after: 777, plus: 5, whole: true },
  { id: 'd4-stair', after: 782, plus: 5, whole: true },
  { id: 'd4-race', after: 789, plus: 5, whole: true },
  { id: 'd4-race-blow1', after: 791, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 794 },
  { id: 'd4-race-blow2', after: 795, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 797 },
  { id: 'd4-ironknight', after: 799, plus: 60, whole: true },
  { id: 'd4-ironknight-fight', after: 800, plus: 300 },
  { id: 'd4-cliffwalk', after: 805, plus: 5, whole: true },
  { id: 'd4-crossed', after: 813, plus: 5, whole: true },
  { id: 'd4-crossed-blow1', after: 816, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 819 },
  { id: 'd4-crossed-blow2', after: 821, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 823 },
  { id: 'd4-crossed-key', after: 825, plus: 5, whole: true },
  { id: 'd4-eastlook', after: 828, plus: 5, whole: true },
  { id: 'd4-gate', after: 835, plus: 5, whole: true },
  { id: 'd4-boss-intro', after: 843, plus: 90, whole: true },
  { id: 'd4-boss-a', after: 844, plus: 600 },
  { id: 'd4-boss-b', after: 844, plus: 800 },
  { id: 'd4-boss-c', after: 844, plus: 1200 },
  { id: 'ow5-noble', after: 876, plus: 40 },
  { id: 'ow5-shrinemouth', after: 886, plus: 5, whole: true },
  { id: 'd5-landing', after: 892, plus: 5, whole: true },
  { id: 'd5-silt', after: 895, plus: 5, whole: true },
  { id: 'd5-bracken', after: 899, plus: 5, whole: true },
  { id: 'd5-chartnave', after: 904, plus: 5, whole: true },
  { id: 'd5-cloister', after: 913, plus: 5, whole: true },
  { id: 'd5-cloister-high', after: 915, plus: 5, whole: true },
  { id: 'd5-thicket', after: 920, plus: 5, whole: true },
  { id: 'd5-bower', after: 929, plus: 5, whole: true },
  { id: 'd5-bower-blow', after: 931, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 934 },
  { id: 'd5-grove', after: 939, plus: 5, whole: true },
  { id: 'd5-rootbound', after: 946, plus: 5, whole: true },
  { id: 'd5-sbracken', after: 948, plus: 5, whole: true },
  { id: 'd5-warden', after: 964, plus: 5, whole: true },
  { id: 'd5-seedvault', after: 972, plus: 5, whole: true },
  { id: 'd5-seed-get', after: 976, plus: 30 },
  { id: 'd5-stake1', after: 980, plus: 5, whole: true },
  { id: 'd5-stake1-high', after: 982, plus: 5, whole: true },
  { id: 'd5-stake1-throw', after: 982, plus: 0, whole: true, until: "g.entities.some(e => e.constructor && /seed/i.test(e.constructor.name))", by: 984 },
  { id: 'd5-stake1-low', after: 984, plus: 60, whole: true },
  { id: 'd5-stake1-cut', after: 988, plus: 5, whole: true },
  { id: 'd5-bolewalk', after: 992, plus: 5, whole: true },
  { id: 'd5-bolewalk-low', after: 998, plus: 60, whole: true },
  { id: 'd5-snave', after: 1006, plus: 5, whole: true },
  { id: 'd5-snave-low', after: 1011, plus: 60, whole: true },
  { id: 'd5-knotted', after: 1028, plus: 5, whole: true },
  { id: 'd5-knotted-low', after: 1035, plus: 60, whole: true },
  { id: 'd5-knotted-2', after: 1036, plus: 60, whole: true },
  { id: 'd5-rootford', after: 1044, plus: 5, whole: true },
  { id: 'd5-rootford-low', after: 1050, plus: 40, whole: true },
  { id: 'd5-rootford-pushed', after: 1057, plus: 5, whole: true },
  { id: 'd5-crossing', after: 1083, plus: 5, whole: true },
  { id: 'd5-longford', after: 1087, plus: 5, whole: true },
  { id: 'd5-longford-low', after: 1093, plus: 60, whole: true },
  { id: 'd5-thornvine', after: 1104, plus: 60, whole: true },
  { id: 'd5-thornvine-fight', after: 1104, plus: 100 },
  { id: 'd5-shrineford', after: 1111, plus: 5, whole: true },
  { id: 'd5-shrineford-2', after: 1116, plus: 60, whole: true },
  { id: 'd5-arch', after: 1131, plus: 5, whole: true },
  { id: 'd5-boss-intro', after: 1138, plus: 90, whole: true },
  { id: 'd5-boss-a', after: 1139, plus: 500 },
  { id: 'd5-boss-b', after: 1139, plus: 800 },
  { id: 'd5-boss-c', after: 1139, plus: 1000 },
  { id: 'ow6-maku', after: 1304, plus: 5, whole: true },
  { id: 'ow6-rod', after: 1305, plus: 5 },
  { id: 'ow6-gate', after: 1335, plus: 5, whole: true },
  { id: 'd6-door', after: 1338, plus: 10, whole: true },
  { id: 'd6-bone', after: 1344, plus: 5, whole: true },
  { id: 'd6-drain', after: 1349, plus: 5, whole: true },
  { id: 'd6-drain-done', after: 1353, plus: 5, whole: true },
  { id: 'd6-kiln', after: 1359, plus: 5, whole: true },
  { id: 'd6-kiln-lit', after: 1377, plus: 60, whole: true },
  { id: 'd6-crypt', after: 1383, plus: 5, whole: true },
  { id: 'd6-crypt-blow', after: 1385, plus: 0, whole: true, until: 'g.player && g.player.bellowsHeld', by: 1387 },
  { id: 'd6-heights', after: 1389, plus: 5, whole: true },
  { id: 'd6-lock', after: 1395, plus: 5, whole: true },
  { id: 'd6-dredgevault', after: 1410, plus: 5, whole: true },
  { id: 'd6-dredge-get', after: 1413, plus: 30 },
  { id: 'd6-slack', after: 1419, plus: 5, whole: true },
  { id: 'd6-slack-cast', after: 1420, plus: 0, whole: true, until: "g.entities.some(e => /dredge|lure|hook/i.test(e.constructor.name))", by: 1422 },
  { id: 'd6-draw', after: 1423, plus: 5, whole: true },
  { id: 'd6-draw-cast', after: 1428, plus: 0, whole: true, until: "g.entities.some(e => /dredge|lure|hook/i.test(e.constructor.name))", by: 1430 },
  { id: 'd6-tally', after: 1435, plus: 5, whole: true },
  { id: 'd6-hauling', after: 1450, plus: 5, whole: true },
  { id: 'd6-upper', after: 1478, plus: 5, whole: true },
  { id: 'd6-tideshade', after: 1482, plus: 60, whole: true },
  { id: 'd6-tideshade-fight', after: 1482, plus: 300 },
  { id: 'd6-mermaid', after: 1487, plus: 5, whole: true },
  { id: 'd6-arches', after: 1494, plus: 5, whole: true },
  { id: 'd6-arches-lens', after: 1497, plus: 0, until: 'g.player && g.player.lensHeld', by: 1499 },
  { id: 'd6-shade', after: 1518, plus: 5, whole: true },
  { id: 'd6-colonnade', after: 1526, plus: 5, whole: true },
  { id: 'd6-colonnade-rod', after: 1528, plus: 5, whole: true },
  { id: 'd6-stand', after: 1540, plus: 5, whole: true },
  { id: 'd6-crossing', after: 1545, plus: 5, whole: true },
  { id: 'd6-bar', after: 1546, plus: 5, whole: true },
  { id: 'd6-sill', after: 1571, plus: 5, whole: true },
  { id: 'd6-gate', after: 1591, plus: 5, whole: true },
  { id: 'd6-shafts', after: 1597, plus: 5, whole: true },
  { id: 'd6-shafts-cast1', after: 1598, plus: 0, whole: true, until: "g.entities.some(e => /dredge|lure|hook/i.test(e.constructor.name))", by: 1600 },
  { id: 'd6-shafts-cast2', after: 1601, plus: 0, whole: true, until: "g.entities.some(e => /dredge|lure|hook/i.test(e.constructor.name))", by: 1603 },
  { id: 'd6-brinehulk', after: 1605, plus: 90, whole: true },
  { id: 'd6-brinehulk-fight', after: 1605, plus: 300 },
  { id: 'd6-stairhead', after: 1630, plus: 5, whole: true },
  { id: 'd6-nereth-intro', after: 1639, plus: 5, whole: true },
  { id: 'd6-nereth-a', after: 1639, plus: 600 },
  { id: 'd6-nereth-b', after: 1639, plus: 900 },
  { id: 'd6-nereth-c', after: 1639, plus: 1500 },
  { id: 'd6-nereth-d', after: 1639, plus: 2200 },
  { id: 'd6-essence', after: 1644, plus: 30 },
  { id: 'd6-end', after: 1646, plus: 0, until: "g.mode === 'theend'", by: 1647 },
];

const D1 = ['3,7','3,6','2,6','3,5','2,5','4,5','3,4','2,4','4,4','3,3','2,3','3,2','4,2','5,2','5,1','4,1','5,3','4,3','2,2','1,2','1,3','1,1','2,1','3,1'];
export const STATIC_SHOTS = [
  { id: 'title', title: true, frames: 400 },
  { id: 'menu-anchor', room: ['d1', 0, 3, 2], tide: 0, whole: false, player: true, keepDialogue: true,
    // Seasons' item page (S176): what is on B and A is up in the status bar,
    // the rest in the grid; the cursor on the Anchor, its name below.
    prep: { script: "Object.assign(g.progress.items, { sword: 1, shield: 1, conch: 1, anchor: 1, cleats: 1, lens: 1 }); g.progress.equipB = 'shield'; g.progress.equipA = 'sword'; g.menu.open(); H.step(60); g.menu.cursor = g.menu.items.findIndex(t => t && t.id === 'anchor'); H.step(30);" } },
];
// The overworld is OVERWORLD_W screens across since S157 (CLAUDE.md: never
// write the width down).
import { OVERWORLD_W } from '../../src/data/overworld.js';
for (let ry = 0; ry < 10; ry++) for (let rx = 0; rx < OVERWORLD_W; rx++) {
  for (const t of [1]) STATIC_SHOTS.push({ id: `ow-t${t}-${rx}-${ry}`, room: ['overworld', 0, rx, ry], tide: t });
}
for (const t of [0, 1, 2]) for (const k of D1) {
  const [rx, ry] = k.split(',').map(Number);
  STATIC_SHOTS.push({ id: `d1map-t${t}-${rx}${ry}`, room: ['d1', 0, rx, ry], tide: t });
}

// Every room of dungeons 2-6 at MID, empty of Link, for the stitched maps.
import { DUNGEON_ROOMS } from './rooms-list.mjs';
for (const [map, keys] of Object.entries(DUNGEON_ROOMS)) for (const k of keys) {
  const [f, rx, ry] = k.split(',').map(Number);
  STATIC_SHOTS.push({ id: `${map}map-${f}-${rx}-${ry}`, room: [map, f, rx, ry], tide: 1 });
}
for (const c of ['cave1', 'cave2', 'cave3', 'cave4', 'cave5', 'cave6', 'caveShipwright']) STATIC_SHOTS.push({ id: `${c}-room`, room: [c, 0, 0, 0], tide: 1 });
STATIC_SHOTS.push({ id: 'cave2-low', room: ['cave2', 0, 0, 0], tide: 0 });
// The optional dungeons' Pieces of Heart (S160, S161), for the heart list.
STATIC_SHOTS.push({ id: 'opt-vault-pan', room: ['vault', 0, 1, 0], tide: 1 });
STATIC_SHOTS.push({ id: 'opt-eyrie-roost', room: ['eyrie', 0, 1, 0], tide: 1 });
STATIC_SHOTS.push({ id: 'opt-palace-chapel', room: ['palace', 1, 0, 2], tide: 0 });
STATIC_SHOTS.push({ id: 'opt-palace-lair', room: ['palace', 0, 1, 0], tide: 1 });

// The Slackwater Cave's mouth, open only at LOW (S155 side content).
STATIC_SHOTS.push({ id: 'ow-t0-1-2', room: ['overworld', 0, 1, 2], tide: 0 });
